package udafApp

object ReadPDR1 {
  def forced()={
    sc.textFile("hdfs://user/matsumoto/sample_pdr1_wide.photoz_demp").
    map{ lines => val elms = lines.split(',')
      val object_id = elms(0).toInt
      

      (
        object_id, ra, dec, coord, skymap_id, tract
        , patch, patch_s, parent_id, deblend_nchild
        , a_g, a_r, a_i, a_z, a_y
        , detect_is_primary
        , merge_footprint_i2, merge_footprint_i, merge_footprint_r, merge_footprint_z, merge_footprint_y, merge_footprint_g, merge_footprint_n921, merge_footprint_n816, merge_footprint_n1010, merge_footprint_n387, merge_footprint_n515, merge_footprint_sky
        , merge_peak_i2, merge_peak_i, merge_peak_r, merge_peak_z, merge_peak_y, merge_peak_g, merge_peak_n921, merge_peak_n816, merge_peak_n1010, merge_peak_n387, merge_peak_n515, merge_peak_sky
        ,detect_is_patch_inner, detect_is_tract_inner
        ,merge_measurement_i2
        ,merge_measurement_i
        ,merge_measurement_r
        ,merge_measurement_z
        ,merge_measurement_y
        ,merge_measurement_g
        ,merge_measurement_n921
        ,merge_measurement_n816
        ,merge_measurement_n1010
        ,merge_measurement_n387
        ,merge_measurement_n515
        ,gflux_naive
        ,gmag_naive
        ,gflux_naive_err
        ,gmag_naive_err
        ,gflux_naive_flags
        ,gflux_sinc
        ,gmag_sinc
        ,gflux_sinc_err
        ,gmag_sinc_err
        ,gflux_sinc_flags
        ,gflux_psf
        ,gmag_psf
        ,gflux_psf_err
        ,gmag_psf_err
        ,gflux_psf_apcorr
        ,gflux_psf_apcorr_err
        ,gflux_psf_flags
        ,gflux_psf_flags_apcorr
        ,gflux_kron
        ,gmag_kron
        ,gflux_kron_err
        ,gmag_kron_err
        ,gflux_kron_radius
        ,gflux_kron_radiusforradius
        ,gflux_kron_psfradius
        ,gflux_kron_apcorr
        ,gflux_kron_apcorr_err
        ,gflux_kron_flags
        ,gflux_kron_flags_edge
        ,gflux_kron_flags_radius
        ,gflux_kron_flags_smallradius
        ,gflux_kron_flags_usedminimumradius
        ,gflux_kron_flags_usedpsfradius
        ,gflux_kron_flags_badshape
        ,gflux_kron_flags_apcorr
        ,gflux_aperture10
        ,gmag_aperture10
        ,gflux_aperture15
        ,gmag_aperture15
        ,gflux_aperture20
        ,gmag_aperture20
        ,gflux_aperture30
        ,gmag_aperture30
        ,gflux_aperture40
        ,gmag_aperture40
        ,gflux_aperture57
        ,gmag_aperture57
        ,gflux_aperture84
        ,gmag_aperture84
        ,gflux_aperture118
        ,gmag_aperture118
        ,gflux_aperture168
        ,gmag_aperture168
        ,gflux_aperture235
        ,gmag_aperture235
        ,gflux_aperture10_err
        ,gmag_aperture10_err
        ,gflux_aperture15_err
        ,gmag_aperture15_err
        ,gflux_aperture20_err
        ,gmag_aperture20_err
        ,gflux_aperture30_err
        ,gmag_aperture30_err
        ,gflux_aperture40_err
        ,gmag_aperture40_err
        ,gflux_aperture57_err
        ,gmag_aperture57_err
        ,gflux_aperture84_err
        ,gmag_aperture84_err
        ,gflux_aperture118_err
        ,gmag_aperture118_err
        ,gflux_aperture168_err
        ,gmag_aperture168_err
        ,gflux_aperture235_err
        ,gmag_aperture235_err
        ,gflux_aperture10_ninterpolatedpixel
        ,gflux_aperture15_ninterpolatedpixel
        ,gflux_aperture20_ninterpolatedpixel
        ,gflux_aperture30_ninterpolatedpixel
        ,gflux_aperture40_ninterpolatedpixel
        ,gflux_aperture57_ninterpolatedpixel
        ,gflux_aperture84_ninterpolatedpixel
        ,gflux_aperture118_ninterpolatedpixel
        ,gflux_aperture168_ninterpolatedpixel
        ,gflux_aperture235_ninterpolatedpixel
        ,gflux_aperture_nprofile
        ,gflux_aperture_flags
        ,gcentroid_naive_ra
        ,gcentroid_naive_dec
        ,gcentroid_naive_flags
        ,gcentroid_sdss_ra
        ,gcentroid_sdss_dec
        ,gcentroid_sdss_err_11
        ,gcentroid_sdss_err_22
        ,gcentroid_sdss_flags
        ,gmultishapelet_psf_inner0
        ,gmultishapelet_psf_inner1
        ,gmultishapelet_psf_inner2
        ,gmultishapelet_psf_inner3
        ,gmultishapelet_psf_inner4
        ,gmultishapelet_psf_inner5
        ,gmultishapelet_psf_outer0
        ,gmultishapelet_psf_outer1
        ,gmultishapelet_psf_outer2
        ,gmultishapelet_psf_ellipse_11
        ,gmultishapelet_psf_ellipse_22
        ,gmultishapelet_psf_ellipse_12
        ,gmultishapelet_psf_chisq
        ,gmultishapelet_psf_integral
        ,gmultishapelet_psf_flags
        ,gmultishapelet_psf_flags_maxiter
        ,gmultishapelet_psf_flags_tinystep
        ,gmultishapelet_psf_flags_constraint_r
        ,gmultishapelet_psf_flags_constraint_q
        ,gshape_sdss_11
        ,gshape_sdss_22
        ,gshape_sdss_12
        ,gshape_sdss_err_11_11
        ,gshape_sdss_err_22_22
        ,gshape_sdss_err_12_12
        ,gshape_sdss_centroid_ra
        ,gshape_sdss_centroid_dec
        ,gshape_sdss_psf_11
        ,gshape_sdss_psf_22
        ,gshape_sdss_psf_12
        ,gshape_sdss_flags
        ,gshape_sdss_centroid_flags
        ,gshape_sdss_flags_unweightedbad
        ,gshape_sdss_flags_unweighted
        ,gshape_sdss_flags_shift
        ,gshape_sdss_flags_maxiter
        ,gshape_sdss_flags_psf
        ,gcmodel_initial_flux
        ,gcmodel_initial_mag
        ,gcmodel_initial_flux_err
        ,gcmodel_initial_mag_err
        ,gcmodel_initial_flux_inner
        ,gcmodel_initial_mag_inner
        ,gcmodel_exp_flux
        ,gcmodel_exp_mag
        ,gcmodel_exp_flux_err
        ,gcmodel_exp_mag_err
        ,gcmodel_exp_flux_inner
        ,gcmodel_exp_mag_inner
        ,gcmodel_dev_flux
        ,gcmodel_dev_mag
        ,gcmodel_dev_flux_err
        ,gcmodel_dev_mag_err
        ,gcmodel_dev_flux_inner
        ,gcmodel_dev_mag_inner
        ,gcmodel_center_ra
        ,gcmodel_center_dec
        ,gcmodel_flux
        ,gcmodel_mag
        ,gcmodel_flux_err
        ,gcmodel_mag_err
        ,gcmodel_flux_inner
        ,gcmodel_mag_inner
        ,gcmodel_fracdev
        ,gcmodel_objective
        ,gcmodel_dev_flux_apcorr
        ,gcmodel_dev_flux_apcorr_err
        ,gcmodel_exp_flux_apcorr
        ,gcmodel_exp_flux_apcorr_err
        ,gcmodel_flux_apcorr
        ,gcmodel_flux_apcorr_err
        ,gcmodel_initial_flux_flags
        ,gcmodel_initial_flags_badreference
        ,gcmodel_initial_flags_numericerror
        ,gcmodel_exp_flux_flags
        ,gcmodel_exp_flags_badreference
        ,gcmodel_exp_flags_numericerror
        ,gcmodel_dev_flux_flags
        ,gcmodel_dev_flags_badreference
        ,gcmodel_dev_flags_numericerror
        ,gcmodel_flux_flags
        ,gcmodel_flags_region_maxarea
        ,gcmodel_flags_region_maxbadpixelfraction
        ,gcmodel_flags_badreference
        ,gcmodel_flags_nopsf
        ,gcmodel_flags_nowcs
        ,gcmodel_flags_nocalib
        ,gcmodel_flags_badcentroid
        ,gcmodel_dev_flux_flags_apcorr
        ,gcmodel_exp_flux_flags_apcorr
        ,gcmodel_flux_flags_apcorr
        ,gcountinputs
        ,gvariance
        ,gclassification_extendedness
        ,gflags_pixel_edge
        ,gflags_pixel_interpolated_any
        ,gflags_pixel_interpolated_center
        ,gflags_pixel_saturated_any
        ,gflags_pixel_saturated_center
        ,gflags_pixel_cr_any
        ,gflags_pixel_cr_center
        ,gflags_pixel_bad
        ,gflags_pixel_suspect_any
        ,gflags_pixel_suspect_center
        ,gflags_pixel_offimage
        ,gflags_pixel_bright_object_center
        ,gflags_pixel_clipped_any
        ,gflags_pixel_bright_object_any
        ,rflux_naive
        ,rmag_naive
        ,rflux_naive_err
        ,rmag_naive_err
        ,rflux_naive_flags
        ,rflux_sinc
        ,rmag_sinc
        ,rflux_sinc_err
        ,rmag_sinc_err
        ,rflux_sinc_flags
        ,rflux_psf
        ,rmag_psf
        ,rflux_psf_err
        ,rmag_psf_err
        ,rflux_psf_apcorr
        ,rflux_psf_apcorr_err
        ,rflux_psf_flags
        ,rflux_psf_flags_apcorr
        ,rflux_kron
        ,rmag_kron
        ,rflux_kron_err
        ,rmag_kron_err
        ,rflux_kron_radius
        ,rflux_kron_radiusforradius
        ,rflux_kron_psfradius
        ,rflux_kron_apcorr
        ,rflux_kron_apcorr_err
        ,rflux_kron_flags
        ,rflux_kron_flags_edge
        ,rflux_kron_flags_radius
        ,rflux_kron_flags_smallradius
        ,rflux_kron_flags_usedminimumradius
        ,rflux_kron_flags_usedpsfradius
        ,rflux_kron_flags_badshape
        ,rflux_kron_flags_apcorr
        ,rflux_aperture10
        ,rmag_aperture10
        ,rflux_aperture15
        ,rmag_aperture15
        ,rflux_aperture20
        ,rmag_aperture20
        ,rflux_aperture30
        ,rmag_aperture30
        ,rflux_aperture40
        ,rmag_aperture40
        ,rflux_aperture57
        ,rmag_aperture57
        ,rflux_aperture84
        ,rmag_aperture84
        ,rflux_aperture118
        ,rmag_aperture118
        ,rflux_aperture168
        ,rmag_aperture168
        ,rflux_aperture235
        ,rmag_aperture235
        ,rflux_aperture10_err
        ,rmag_aperture10_err
        ,rflux_aperture15_err
        ,rmag_aperture15_err
        ,rflux_aperture20_err
        ,rmag_aperture20_err
        ,rflux_aperture30_err
        ,rmag_aperture30_err
        ,rflux_aperture40_err
        ,rmag_aperture40_err
        ,rflux_aperture57_err
        ,rmag_aperture57_err
        ,rflux_aperture84_err
        ,rmag_aperture84_err
        ,rflux_aperture118_err
        ,rmag_aperture118_err
        ,rflux_aperture168_err
        ,rmag_aperture168_err
        ,rflux_aperture235_err
        ,rmag_aperture235_err
        ,rflux_aperture10_ninterpolatedpixel
        ,rflux_aperture15_ninterpolatedpixel
        ,rflux_aperture20_ninterpolatedpixel
        ,rflux_aperture30_ninterpolatedpixel
        ,rflux_aperture40_ninterpolatedpixel
        ,rflux_aperture57_ninterpolatedpixel
        ,rflux_aperture84_ninterpolatedpixel
        ,rflux_aperture118_ninterpolatedpixel
        ,rflux_aperture168_ninterpolatedpixel
        ,rflux_aperture235_ninterpolatedpixel
        ,rflux_aperture_nprofile
        ,rflux_aperture_flags
        ,rcentroid_naive_ra
        ,rcentroid_naive_dec
        ,rcentroid_naive_flags
        ,rcentroid_sdss_ra
        ,rcentroid_sdss_dec
        ,rcentroid_sdss_err_11
        ,rcentroid_sdss_err_22
        ,rcentroid_sdss_flags
        ,rmultishapelet_psf_inner0
        ,rmultishapelet_psf_inner1
        ,rmultishapelet_psf_inner2
        ,rmultishapelet_psf_inner3
        ,rmultishapelet_psf_inner4
        ,rmultishapelet_psf_inner5
        ,rmultishapelet_psf_outer0
        ,rmultishapelet_psf_outer1
        ,rmultishapelet_psf_outer2
        ,rmultishapelet_psf_ellipse_11
        ,rmultishapelet_psf_ellipse_22
        ,rmultishapelet_psf_ellipse_12
        ,rmultishapelet_psf_chisq
        ,rmultishapelet_psf_integral
        ,rmultishapelet_psf_flags
        ,rmultishapelet_psf_flags_maxiter
        ,rmultishapelet_psf_flags_tinystep
        ,rmultishapelet_psf_flags_constraint_r
        ,rmultishapelet_psf_flags_constraint_q
        ,rshape_sdss_11
        ,rshape_sdss_22
        ,rshape_sdss_12
        ,rshape_sdss_err_11_11
        ,rshape_sdss_err_22_22
        ,rshape_sdss_err_12_12
        ,rshape_sdss_centroid_ra
        ,rshape_sdss_centroid_dec
        ,rshape_sdss_psf_11
        ,rshape_sdss_psf_22
        ,rshape_sdss_psf_12
        ,rshape_sdss_flags
        ,rshape_sdss_centroid_flags
        ,rshape_sdss_flags_unweightedbad
        ,rshape_sdss_flags_unweighted
        ,rshape_sdss_flags_shift
        ,rshape_sdss_flags_maxiter
        ,rshape_sdss_flags_psf
        ,rcmodel_initial_flux
        ,rcmodel_initial_mag
        ,rcmodel_initial_flux_err
        ,rcmodel_initial_mag_err
        ,rcmodel_initial_flux_inner
        ,rcmodel_initial_mag_inner
        ,rcmodel_exp_flux
        ,rcmodel_exp_mag
        ,rcmodel_exp_flux_err
        ,rcmodel_exp_mag_err
        ,rcmodel_exp_flux_inner
        ,rcmodel_exp_mag_inner
        ,rcmodel_dev_flux
        ,rcmodel_dev_mag
        ,rcmodel_dev_flux_err
        ,rcmodel_dev_mag_err
        ,rcmodel_dev_flux_inner
        ,rcmodel_dev_mag_inner
        ,rcmodel_center_ra
        ,rcmodel_center_dec
        ,rcmodel_flux
        ,rcmodel_mag
        ,rcmodel_flux_err
        ,rcmodel_mag_err
        ,rcmodel_flux_inner
        ,rcmodel_mag_inner
        ,rcmodel_fracdev
        ,rcmodel_objective
        ,rcmodel_dev_flux_apcorr
        ,rcmodel_dev_flux_apcorr_err
        ,rcmodel_exp_flux_apcorr
        ,rcmodel_exp_flux_apcorr_err
        ,rcmodel_flux_apcorr
        ,rcmodel_flux_apcorr_err
        ,rcmodel_initial_flux_flags
        ,rcmodel_initial_flags_badreference
        ,rcmodel_initial_flags_numericerror
        ,rcmodel_exp_flux_flags
        ,rcmodel_exp_flags_badreference
        ,rcmodel_exp_flags_numericerror
        ,rcmodel_dev_flux_flags
        ,rcmodel_dev_flags_badreference
        ,rcmodel_dev_flags_numericerror
        ,rcmodel_flux_flags
        ,rcmodel_flags_region_maxarea
        ,rcmodel_flags_region_maxbadpixelfraction
        ,rcmodel_flags_badreference
        ,rcmodel_flags_nopsf
        ,rcmodel_flags_nowcs
        ,rcmodel_flags_nocalib
        ,rcmodel_flags_badcentroid
        ,rcmodel_dev_flux_flags_apcorr
        ,rcmodel_exp_flux_flags_apcorr
        ,rcmodel_flux_flags_apcorr
        ,rcountinputs
        ,rvariance
        ,rclassification_extendedness
        ,rflags_pixel_edge
        ,rflags_pixel_interpolated_any
        ,rflags_pixel_interpolated_center
        ,rflags_pixel_saturated_any
        ,rflags_pixel_saturated_center
        ,rflags_pixel_cr_any
        ,rflags_pixel_cr_center
        ,rflags_pixel_bad
        ,rflags_pixel_suspect_any
        ,rflags_pixel_suspect_center
        ,rflags_pixel_offimage
        ,rflags_pixel_bright_object_center
        ,rflags_pixel_clipped_any
        ,rflags_pixel_bright_object_any
        ,iflux_naive
        ,imag_naive
        ,iflux_naive_err
        ,imag_naive_err
        ,iflux_naive_flags
        ,iflux_sinc
        ,imag_sinc
        ,iflux_sinc_err
        ,imag_sinc_err
        ,iflux_sinc_flags
        ,iflux_psf
        ,imag_psf
        ,iflux_psf_err
        ,imag_psf_err
        ,iflux_psf_apcorr
        ,iflux_psf_apcorr_err
        ,iflux_psf_flags
        ,iflux_psf_flags_apcorr
        ,iflux_kron
        ,imag_kron
        ,iflux_kron_err
        ,imag_kron_err
        ,iflux_kron_radius
        ,iflux_kron_radiusforradius
        ,iflux_kron_psfradius
        ,iflux_kron_apcorr
        ,iflux_kron_apcorr_err
        ,iflux_kron_flags
        ,iflux_kron_flags_edge
        ,iflux_kron_flags_radius
        ,iflux_kron_flags_smallradius
        ,iflux_kron_flags_usedminimumradius
        ,iflux_kron_flags_usedpsfradius
        ,iflux_kron_flags_badshape
        ,iflux_kron_flags_apcorr
        ,iflux_aperture10
        ,imag_aperture10
        ,iflux_aperture15
        ,imag_aperture15
        ,iflux_aperture20
        ,imag_aperture20
        ,iflux_aperture30
        ,imag_aperture30
        ,iflux_aperture40
        ,imag_aperture40
        ,iflux_aperture57
        ,imag_aperture57
        ,iflux_aperture84
        ,imag_aperture84
        ,iflux_aperture118
        ,imag_aperture118
        ,iflux_aperture168
        ,imag_aperture168
        ,iflux_aperture235
        ,imag_aperture235
        ,iflux_aperture10_err
        ,imag_aperture10_err
        ,iflux_aperture15_err
        ,imag_aperture15_err
        ,iflux_aperture20_err
        ,imag_aperture20_err
        ,iflux_aperture30_err
        ,imag_aperture30_err
        ,iflux_aperture40_err
        ,imag_aperture40_err
        ,iflux_aperture57_err
        ,imag_aperture57_err
        ,iflux_aperture84_err
        ,imag_aperture84_err
        ,iflux_aperture118_err
        ,imag_aperture118_err
        ,iflux_aperture168_err
        ,imag_aperture168_err
        ,iflux_aperture235_err
        ,imag_aperture235_err
        ,iflux_aperture10_ninterpolatedpixel
        ,iflux_aperture15_ninterpolatedpixel
        ,iflux_aperture20_ninterpolatedpixel
        ,iflux_aperture30_ninterpolatedpixel
        ,iflux_aperture40_ninterpolatedpixel
        ,iflux_aperture57_ninterpolatedpixel
        ,iflux_aperture84_ninterpolatedpixel
        ,iflux_aperture118_ninterpolatedpixel
        ,iflux_aperture168_ninterpolatedpixel
        ,iflux_aperture235_ninterpolatedpixel
        ,iflux_aperture_nprofile
        ,iflux_aperture_flags
        ,icentroid_naive_ra
        ,icentroid_naive_dec
        ,icentroid_naive_flags
        ,icentroid_sdss_ra
        ,icentroid_sdss_dec
        ,icentroid_sdss_err_11
        ,icentroid_sdss_err_22
        ,icentroid_sdss_flags
        ,imultishapelet_psf_inner0
        ,imultishapelet_psf_inner1
        ,imultishapelet_psf_inner2
        ,imultishapelet_psf_inner3
        ,imultishapelet_psf_inner4
        ,imultishapelet_psf_inner5
        ,imultishapelet_psf_outer0
        ,imultishapelet_psf_outer1
        ,imultishapelet_psf_outer2
        ,imultishapelet_psf_ellipse_11
        ,imultishapelet_psf_ellipse_22
        ,imultishapelet_psf_ellipse_12
        ,imultishapelet_psf_chisq
        ,imultishapelet_psf_integral
        ,imultishapelet_psf_flags
        ,imultishapelet_psf_flags_maxiter
        ,imultishapelet_psf_flags_tinystep
        ,imultishapelet_psf_flags_constraint_r
        ,imultishapelet_psf_flags_constraint_q
        ,ishape_sdss_11
        ,ishape_sdss_22
        ,ishape_sdss_12
        ,ishape_sdss_err_11_11
        ,ishape_sdss_err_22_22
        ,ishape_sdss_err_12_12
        ,ishape_sdss_centroid_ra
        ,ishape_sdss_centroid_dec
        ,ishape_sdss_psf_11
        ,ishape_sdss_psf_22
        ,ishape_sdss_psf_12
        ,ishape_sdss_flags
        ,ishape_sdss_centroid_flags
        ,ishape_sdss_flags_unweightedbad
        ,ishape_sdss_flags_unweighted
        ,ishape_sdss_flags_shift
        ,ishape_sdss_flags_maxiter
        ,ishape_sdss_flags_psf
        ,icmodel_initial_flux
        ,icmodel_initial_mag
        ,icmodel_initial_flux_err
        ,icmodel_initial_mag_err
        ,icmodel_initial_flux_inner
        ,icmodel_initial_mag_inner
        ,icmodel_exp_flux
        ,icmodel_exp_mag
        ,icmodel_exp_flux_err
        ,icmodel_exp_mag_err
        ,icmodel_exp_flux_inner
        ,icmodel_exp_mag_inner
        ,icmodel_dev_flux
        ,icmodel_dev_mag
        ,icmodel_dev_flux_err
        ,icmodel_dev_mag_err
        ,icmodel_dev_flux_inner
        ,icmodel_dev_mag_inner
        ,icmodel_center_ra
        ,icmodel_center_dec
        ,icmodel_flux
        ,icmodel_mag
        ,icmodel_flux_err
        ,icmodel_mag_err
        ,icmodel_flux_inner
        ,icmodel_mag_inner
        ,icmodel_fracdev
        ,icmodel_objective
        ,icmodel_dev_flux_apcorr
        ,icmodel_dev_flux_apcorr_err
        ,icmodel_exp_flux_apcorr
        ,icmodel_exp_flux_apcorr_err
        ,icmodel_flux_apcorr
        ,icmodel_flux_apcorr_err
        ,icmodel_initial_flux_flags
        ,icmodel_initial_flags_badreference
        ,icmodel_initial_flags_numericerror
        ,icmodel_exp_flux_flags
        ,icmodel_exp_flags_badreference
        ,icmodel_exp_flags_numericerror
        ,icmodel_dev_flux_flags
        ,icmodel_dev_flags_badreference
        ,icmodel_dev_flags_numericerror
        ,icmodel_flux_flags
        ,icmodel_flags_region_maxarea
        ,icmodel_flags_region_maxbadpixelfraction
        ,icmodel_flags_badreference
        ,icmodel_flags_nopsf
        ,icmodel_flags_nowcs
        ,icmodel_flags_nocalib
        ,icmodel_flags_badcentroid
        ,icmodel_dev_flux_flags_apcorr
        ,icmodel_exp_flux_flags_apcorr
        ,icmodel_flux_flags_apcorr
        ,icountinputs
        ,ivariance
        ,iclassification_extendedness
        ,iflags_pixel_edge
        ,iflags_pixel_interpolated_any
        ,iflags_pixel_interpolated_center
        ,iflags_pixel_saturated_any
        ,iflags_pixel_saturated_center
        ,iflags_pixel_cr_any
        ,iflags_pixel_cr_center
        ,iflags_pixel_bad
        ,iflags_pixel_suspect_any
        ,iflags_pixel_suspect_center
        ,iflags_pixel_offimage
        ,iflags_pixel_bright_object_center
        ,iflags_pixel_clipped_any
        ,iflags_pixel_bright_object_any
        ,zflux_naive
        ,zmag_naive
        ,zflux_naive_err
        ,zmag_naive_err
        ,zflux_naive_flags
        ,zflux_sinc
        ,zmag_sinc
        ,zflux_sinc_err
        ,zmag_sinc_err
        ,zflux_sinc_flags
        ,zflux_psf
        ,zmag_psf
        ,zflux_psf_err
        ,zmag_psf_err
        ,zflux_psf_apcorr
        ,zflux_psf_apcorr_err
        ,zflux_psf_flags
        ,zflux_psf_flags_apcorr
        ,zflux_kron
        ,zmag_kron
        ,zflux_kron_err
        ,zmag_kron_err
        ,zflux_kron_radius
        ,zflux_kron_radiusforradius
        ,zflux_kron_psfradius
        ,zflux_kron_apcorr
        ,zflux_kron_apcorr_err
        ,zflux_kron_flags
        ,zflux_kron_flags_edge
        ,zflux_kron_flags_radius
        ,zflux_kron_flags_smallradius
        ,zflux_kron_flags_usedminimumradius
        ,zflux_kron_flags_usedpsfradius
        ,zflux_kron_flags_badshape
        ,zflux_kron_flags_apcorr
        ,zflux_aperture10
        ,zmag_aperture10
        ,zflux_aperture15
        ,zmag_aperture15
        ,zflux_aperture20
        ,zmag_aperture20
        ,zflux_aperture30
        ,zmag_aperture30
        ,zflux_aperture40
        ,zmag_aperture40
        ,zflux_aperture57
        ,zmag_aperture57
        ,zflux_aperture84
        ,zmag_aperture84
        ,zflux_aperture118
        ,zmag_aperture118
        ,zflux_aperture168
        ,zmag_aperture168
        ,zflux_aperture235
        ,zmag_aperture235
        ,zflux_aperture10_err
        ,zmag_aperture10_err
        ,zflux_aperture15_err
        ,zmag_aperture15_err
        ,zflux_aperture20_err
        ,zmag_aperture20_err
        ,zflux_aperture30_err
        ,zmag_aperture30_err
        ,zflux_aperture40_err
        ,zmag_aperture40_err
        ,zflux_aperture57_err
        ,zmag_aperture57_err
        ,zflux_aperture84_err
        ,zmag_aperture84_err
        ,zflux_aperture118_err
        ,zmag_aperture118_err
        ,zflux_aperture168_err
        ,zmag_aperture168_err
        ,zflux_aperture235_err
        ,zmag_aperture235_err
        ,zflux_aperture10_ninterpolatedpixel
        ,zflux_aperture15_ninterpolatedpixel
        ,zflux_aperture20_ninterpolatedpixel
        ,zflux_aperture30_ninterpolatedpixel
        ,zflux_aperture40_ninterpolatedpixel
        ,zflux_aperture57_ninterpolatedpixel
        ,zflux_aperture84_ninterpolatedpixel
        ,zflux_aperture118_ninterpolatedpixel
        ,zflux_aperture168_ninterpolatedpixel
        ,zflux_aperture235_ninterpolatedpixel
        ,zflux_aperture_nprofile
        ,zflux_aperture_flags
        ,zcentroid_naive_ra
        ,zcentroid_naive_dec
        ,zcentroid_naive_flags
        ,zcentroid_sdss_ra
        ,zcentroid_sdss_dec
        ,zcentroid_sdss_err_11
        ,zcentroid_sdss_err_22
        ,zcentroid_sdss_flags
        ,zmultishapelet_psf_inner0
        ,zmultishapelet_psf_inner1
        ,zmultishapelet_psf_inner2
        ,zmultishapelet_psf_inner3
        ,zmultishapelet_psf_inner4
        ,zmultishapelet_psf_inner5
        ,zmultishapelet_psf_outer0
        ,zmultishapelet_psf_outer1
        ,zmultishapelet_psf_outer2
        ,zmultishapelet_psf_ellipse_11
        ,zmultishapelet_psf_ellipse_22
        ,zmultishapelet_psf_ellipse_12
        ,zmultishapelet_psf_chisq
        ,zmultishapelet_psf_integral
        ,zmultishapelet_psf_flags
        ,zmultishapelet_psf_flags_maxiter
        ,zmultishapelet_psf_flags_tinystep
        ,zmultishapelet_psf_flags_constraint_r
        ,zmultishapelet_psf_flags_constraint_q
        ,zshape_sdss_11
        ,zshape_sdss_22
        ,zshape_sdss_12
        ,zshape_sdss_err_11_11
        ,zshape_sdss_err_22_22
        ,zshape_sdss_err_12_12
        ,zshape_sdss_centroid_ra
        ,zshape_sdss_centroid_dec
        ,zshape_sdss_psf_11
        ,zshape_sdss_psf_22
        ,zshape_sdss_psf_12
        ,zshape_sdss_flags
        ,zshape_sdss_centroid_flags
        ,zshape_sdss_flags_unweightedbad
        ,zshape_sdss_flags_unweighted
        ,zshape_sdss_flags_shift
        ,zshape_sdss_flags_maxiter
        ,zshape_sdss_flags_psf
        ,zcmodel_initial_flux
        ,zcmodel_initial_mag
        ,zcmodel_initial_flux_err
        ,zcmodel_initial_mag_err
        ,zcmodel_initial_flux_inner
        ,zcmodel_initial_mag_inner
        ,zcmodel_exp_flux
        ,zcmodel_exp_mag
        ,zcmodel_exp_flux_err
        ,zcmodel_exp_mag_err
        ,zcmodel_exp_flux_inner
        ,zcmodel_exp_mag_inner
        ,zcmodel_dev_flux
        ,zcmodel_dev_mag
        ,zcmodel_dev_flux_err
        ,zcmodel_dev_mag_err
        ,zcmodel_dev_flux_inner
        ,zcmodel_dev_mag_inner
        ,zcmodel_center_ra
        ,zcmodel_center_dec
        ,zcmodel_flux
        ,zcmodel_mag
        ,zcmodel_flux_err
        ,zcmodel_mag_err
        ,zcmodel_flux_inner
        ,zcmodel_mag_inner
        ,zcmodel_fracdev
        ,zcmodel_objective
        ,zcmodel_dev_flux_apcorr
        ,zcmodel_dev_flux_apcorr_err
        ,zcmodel_exp_flux_apcorr
        ,zcmodel_exp_flux_apcorr_err
        ,zcmodel_flux_apcorr
        ,zcmodel_flux_apcorr_err
        ,zcmodel_initial_flux_flags
        ,zcmodel_initial_flags_badreference
        ,zcmodel_initial_flags_numericerror
        ,zcmodel_exp_flux_flags
        ,zcmodel_exp_flags_badreference
        ,zcmodel_exp_flags_numericerror
        ,zcmodel_dev_flux_flags
        ,zcmodel_dev_flags_badreference
        ,zcmodel_dev_flags_numericerror
        ,zcmodel_flux_flags
        ,zcmodel_flags_region_maxarea
        ,zcmodel_flags_region_maxbadpixelfraction
        ,zcmodel_flags_badreference
        ,zcmodel_flags_nopsf
        ,zcmodel_flags_nowcs
        ,zcmodel_flags_nocalib
        ,zcmodel_flags_badcentroid
        ,zcmodel_dev_flux_flags_apcorr
        ,zcmodel_exp_flux_flags_apcorr
        ,zcmodel_flux_flags_apcorr
        ,zcountinputs
        ,zvariance
        ,zclassification_extendedness
        ,zflags_pixel_edge
        ,zflags_pixel_interpolated_any
        ,zflags_pixel_interpolated_center
        ,zflags_pixel_saturated_any
        ,zflags_pixel_saturated_center
        ,zflags_pixel_cr_any
        ,zflags_pixel_cr_center
        ,zflags_pixel_bad
        ,zflags_pixel_suspect_any
        ,zflags_pixel_suspect_center
        ,zflags_pixel_offimage
        ,zflags_pixel_bright_object_center
        ,zflags_pixel_clipped_any
        ,zflags_pixel_bright_object_any
        ,yflux_naive
        ,ymag_naive
        ,yflux_naive_err
        ,ymag_naive_err
        ,yflux_naive_flags
        ,yflux_sinc
        ,ymag_sinc
        ,yflux_sinc_err
        ,ymag_sinc_err
        ,yflux_sinc_flags
        ,yflux_psf
        ,ymag_psf
        ,yflux_psf_err
        ,ymag_psf_err
        ,yflux_psf_apcorr
        ,yflux_psf_apcorr_err
        ,yflux_psf_flags
        ,yflux_psf_flags_apcorr
        ,yflux_kron
        ,ymag_kron
        ,yflux_kron_err
        ,ymag_kron_err
        ,yflux_kron_radius
        ,yflux_kron_radiusforradius
        ,yflux_kron_psfradius
        ,yflux_kron_apcorr
        ,yflux_kron_apcorr_err
        ,yflux_kron_flags
        ,yflux_kron_flags_edge
        ,yflux_kron_flags_radius
        ,yflux_kron_flags_smallradius
        ,yflux_kron_flags_usedminimumradius
        ,yflux_kron_flags_usedpsfradius
        ,yflux_kron_flags_badshape
        ,yflux_kron_flags_apcorr
        ,yflux_aperture10
        ,ymag_aperture10
        ,yflux_aperture15
        ,ymag_aperture15
        ,yflux_aperture20
        ,ymag_aperture20
        ,yflux_aperture30
        ,ymag_aperture30
        ,yflux_aperture40
        ,ymag_aperture40
        ,yflux_aperture57
        ,ymag_aperture57
        ,yflux_aperture84
        ,ymag_aperture84
        ,yflux_aperture118
        ,ymag_aperture118
        ,yflux_aperture168
        ,ymag_aperture168
        ,yflux_aperture235
        ,ymag_aperture235
        ,yflux_aperture10_err
        ,ymag_aperture10_err
        ,yflux_aperture15_err
        ,ymag_aperture15_err
        ,yflux_aperture20_err
        ,ymag_aperture20_err
        ,yflux_aperture30_err
        ,ymag_aperture30_err
        ,yflux_aperture40_err
        ,ymag_aperture40_err
        ,yflux_aperture57_err
        ,ymag_aperture57_err
        ,yflux_aperture84_err
        ,ymag_aperture84_err
        ,yflux_aperture118_err
        ,ymag_aperture118_err
        ,yflux_aperture168_err
        ,ymag_aperture168_err
        ,yflux_aperture235_err
        ,ymag_aperture235_err
        ,yflux_aperture10_ninterpolatedpixel
        ,yflux_aperture15_ninterpolatedpixel
        ,yflux_aperture20_ninterpolatedpixel
        ,yflux_aperture30_ninterpolatedpixel
        ,yflux_aperture40_ninterpolatedpixel
        ,yflux_aperture57_ninterpolatedpixel
        ,yflux_aperture84_ninterpolatedpixel
        ,yflux_aperture118_ninterpolatedpixel
        ,yflux_aperture168_ninterpolatedpixel
        ,yflux_aperture235_ninterpolatedpixel
        ,yflux_aperture_nprofile
        ,yflux_aperture_flags
        ,ycentroid_naive_ra
        ,ycentroid_naive_dec
        ,ycentroid_naive_flags
        ,ycentroid_sdss_ra
        ,ycentroid_sdss_dec
        ,ycentroid_sdss_err_11
        ,ycentroid_sdss_err_22
        ,ycentroid_sdss_flags
        ,ymultishapelet_psf_inner0
        ,ymultishapelet_psf_inner1
        ,ymultishapelet_psf_inner2
        ,ymultishapelet_psf_inner3
        ,ymultishapelet_psf_inner4
        ,ymultishapelet_psf_inner5
        ,ymultishapelet_psf_outer0
        ,ymultishapelet_psf_outer1
        ,ymultishapelet_psf_outer2
        ,ymultishapelet_psf_ellipse_11
        ,ymultishapelet_psf_ellipse_22
        ,ymultishapelet_psf_ellipse_12
        ,ymultishapelet_psf_chisq
        ,ymultishapelet_psf_integral
        ,ymultishapelet_psf_flags
        ,ymultishapelet_psf_flags_maxiter
        ,ymultishapelet_psf_flags_tinystep
        ,ymultishapelet_psf_flags_constraint_r
        ,ymultishapelet_psf_flags_constraint_q
        ,yshape_sdss_11
        ,yshape_sdss_22
        ,yshape_sdss_12
        ,yshape_sdss_err_11_11
        ,yshape_sdss_err_22_22
        ,yshape_sdss_err_12_12
        ,yshape_sdss_centroid_ra
        ,yshape_sdss_centroid_dec
        ,yshape_sdss_psf_11
        ,yshape_sdss_psf_22
        ,yshape_sdss_psf_12
        ,yshape_sdss_flags
        ,yshape_sdss_centroid_flags
        ,yshape_sdss_flags_unweightedbad
        ,yshape_sdss_flags_unweighted
        ,yshape_sdss_flags_shift
        ,yshape_sdss_flags_maxiter
        ,yshape_sdss_flags_psf
        ,ycmodel_initial_flux
        ,ycmodel_initial_mag
        ,ycmodel_initial_flux_err
        ,ycmodel_initial_mag_err
        ,ycmodel_initial_flux_inner
        ,ycmodel_initial_mag_inner
        ,ycmodel_exp_flux
        ,ycmodel_exp_mag
        ,ycmodel_exp_flux_err
        ,ycmodel_exp_mag_err
        ,ycmodel_exp_flux_inner
        ,ycmodel_exp_mag_inner
        ,ycmodel_dev_flux
        ,ycmodel_dev_mag
        ,ycmodel_dev_flux_err
        ,ycmodel_dev_mag_err
        ,ycmodel_dev_flux_inner
        ,ycmodel_dev_mag_inner
        ,ycmodel_center_ra
        ,ycmodel_center_dec
        ,ycmodel_flux
        ,ycmodel_mag
        ,ycmodel_flux_err
        ,ycmodel_mag_err
        ,ycmodel_flux_inner
        ,ycmodel_mag_inner
        ,ycmodel_fracdev
        ,ycmodel_objective
        ,ycmodel_dev_flux_apcorr
        ,ycmodel_dev_flux_apcorr_err
        ,ycmodel_exp_flux_apcorr
        ,ycmodel_exp_flux_apcorr_err
        ,ycmodel_flux_apcorr
        ,ycmodel_flux_apcorr_err
        ,ycmodel_initial_flux_flags
        ,ycmodel_initial_flags_badreference
        ,ycmodel_initial_flags_numericerror
        ,ycmodel_exp_flux_flags
        ,ycmodel_exp_flags_badreference
        ,ycmodel_exp_flags_numericerror
        ,ycmodel_dev_flux_flags
        ,ycmodel_dev_flags_badreference
        ,ycmodel_dev_flags_numericerror
        ,ycmodel_flux_flags
        ,ycmodel_flags_region_maxarea
        ,ycmodel_flags_region_maxbadpixelfraction
        ,ycmodel_flags_badreference
        ,ycmodel_flags_nopsf
        ,ycmodel_flags_nowcs
        ,ycmodel_flags_nocalib
        ,ycmodel_flags_badcentroid
        ,ycmodel_dev_flux_flags_apcorr
        ,ycmodel_exp_flux_flags_apcorr
        ,ycmodel_flux_flags_apcorr
        ,ycountinputs
        ,yvariance
        ,yclassification_extendedness
        ,yflags_pixel_edge
        ,yflags_pixel_interpolated_any
        ,yflags_pixel_interpolated_center
        ,yflags_pixel_saturated_any
        ,yflags_pixel_saturated_center
        ,yflags_pixel_cr_any
        ,yflags_pixel_cr_center
        ,yflags_pixel_bad
        ,yflags_pixel_suspect_any
        ,yflags_pixel_suspect_center
        ,yflags_pixel_offimage
        ,yflags_pixel_bright_object_center
        ,yflags_pixel_clipped_any
        ,yflags_pixel_bright_object_any
      )
    }
  }

  def meas()={
    sc.textFile("hdfs://user/matsumoto/sample_pdr1_wide.photoz_demp").
      map{ lines => val elms = lines.split(",")
        (
          object_id
          ,gra
          ,gdec
          ,gcoord
          ,rra
          ,rdec
          ,rcoord
          ,ira
          ,idec
          ,icoord
          ,zra
          ,zdec
          ,zcoord
          ,yra
          ,ydec
          ,ycoord
          ,skymap_id
          ,tract
          ,patch
          ,patch_s
          ,parent_id bigint
          ,deblend_nchild
          ,merge_footprint_i2
          ,merge_footprint_i
          ,merge_footprint_r
          ,merge_footprint_z
          ,merge_footprint_y
          ,merge_footprint_g
          ,merge_footprint_n921
          ,merge_footprint_n816
          ,merge_footprint_n1010
          ,merge_footprint_n387
          ,merge_footprint_n515
          ,merge_footprint_sky
          ,merge_peak_i2
          ,merge_peak_i
          ,merge_peak_r
          ,merge_peak_z
          ,merge_peak_y
          ,merge_peak_g
          ,merge_peak_n921
          ,merge_peak_n816
          ,merge_peak_n1010
          ,merge_peak_n387
          ,merge_peak_n515
          ,merge_peak_sky
          ,gflux_naive
          ,gmag_naive
          ,gflux_naive_err
          ,gmag_naive_err
          ,gflux_naive_flags
          ,gflux_sinc
          ,gmag_sinc
          ,gflux_sinc_err
          ,gmag_sinc_err
          ,gflux_sinc_flags
          ,gflux_psf
          ,gmag_psf
          ,gflux_psf_err
          ,gmag_psf_err
          ,gflux_psf_apcorr
          ,gflux_psf_apcorr_err
          ,gflux_psf_flags
          ,gflux_psf_flags_apcorr
          ,gflux_kron
          ,gmag_kron
          ,gflux_kron_err
          ,gmag_kron_err
          ,gflux_kron_radius
          ,gflux_kron_radiusforradius
          ,gflux_kron_psfradius
          ,gflux_kron_apcorr
          ,gflux_kron_apcorr_err
          ,gflux_kron_flags
          ,gflux_kron_flags_edge
          ,gflux_kron_flags_radius
          ,gflux_kron_flags_smallradius
          ,gflux_kron_flags_usedminimumradius
          ,gflux_kron_flags_usedpsfradius
          ,gflux_kron_flags_badshape
          ,gflux_kron_flags_apcorr
          ,gflux_gaussian
          ,gmag_gaussian
          ,gflux_gaussian_err
          ,gmag_gaussian_err
          ,gflux_gaussian_apcorr
          ,gflux_gaussian_apcorr_err
          ,gflux_gaussian_flags
          ,gflux_gaussian_flags_apcorr
          ,gcmodel_initial_flux
          ,gcmodel_initial_mag
          ,gcmodel_initial_flux_err
          ,gcmodel_initial_mag_err
          ,gcmodel_initial_flux_inner
          ,gcmodel_initial_mag_inner
          ,gcmodel_initial_ellipse_11
          ,gcmodel_initial_ellipse_22
          ,gcmodel_initial_ellipse_12
          ,gcmodel_initial_objective
          ,gcmodel_initial_nonlinear0
          ,gcmodel_initial_nonlinear1
          ,gcmodel_initial_nonlinear2
          ,gcmodel_initial_fixed0
          ,gcmodel_initial_fixed1
          ,gcmodel_initial_niter
          ,gcmodel_initial_time
          ,gcmodel_exp_flux
          ,gcmodel_exp_mag
          ,gcmodel_exp_flux_err
          ,gcmodel_exp_mag_err
          ,gcmodel_exp_flux_inner
          ,gcmodel_exp_mag_inner
          ,gcmodel_exp_ellipse_11
          ,gcmodel_exp_ellipse_22
          ,gcmodel_exp_ellipse_12
          ,gcmodel_exp_objective
          ,gcmodel_exp_nonlinear0
          ,gcmodel_exp_nonlinear1
          ,gcmodel_exp_nonlinear2
          ,gcmodel_exp_fixed0
          ,gcmodel_exp_fixed1
          ,gcmodel_exp_niter
          ,gcmodel_exp_time
          ,gcmodel_dev_flux
          ,gcmodel_dev_mag
          ,gcmodel_dev_flux_err
          ,gcmodel_dev_mag_err
          ,gcmodel_dev_flux_inner
          ,gcmodel_dev_mag_inner
          ,gcmodel_dev_ellipse_11
          ,gcmodel_dev_ellipse_22
          ,gcmodel_dev_ellipse_12
          ,gcmodel_dev_objective
          ,gcmodel_dev_nonlinear0
          ,gcmodel_dev_nonlinear1
          ,gcmodel_dev_nonlinear2
          ,gcmodel_dev_fixed0
          ,gcmodel_dev_fixed1
          ,gcmodel_dev_niter
          ,gcmodel_dev_time
          ,gcmodel_center_ra
          ,gcmodel_center_dec
          ,gcmodel_flux
          ,gcmodel_mag
          ,gcmodel_flux_err
          ,gcmodel_mag_err
          ,gcmodel_flux_inner
          ,gcmodel_mag_inner
          ,gcmodel_fracdev
          ,gcmodel_objective
          ,gcmodel_ellipse_11
          ,gcmodel_ellipse_22
          ,gcmodel_ellipse_12
          ,gcmodel_region_initial_ellipse_11
          ,gcmodel_region_initial_ellipse_22
          ,gcmodel_region_initial_ellipse_12
          ,gcmodel_region_final_ellipse_11
          ,gcmodel_region_final_ellipse_22
          ,gcmodel_region_final_ellipse_12
          ,gcmodel_dev_flux_apcorr
          ,gcmodel_dev_flux_apcorr_err
          ,gcmodel_exp_flux_apcorr
          ,gcmodel_exp_flux_apcorr_err
          ,gcmodel_flux_apcorr
          ,gcmodel_flux_apcorr_err
          ,gcmodel_initial_flux_flags
          ,gcmodel_initial_flags_trsmall
          ,gcmodel_initial_flags_maxiter
          ,gcmodel_initial_flags_numericerror
          ,gcmodel_exp_flux_flags
          ,gcmodel_exp_flags_trsmall
          ,gcmodel_exp_flags_maxiter
          ,gcmodel_exp_flags_numericerror
          ,gcmodel_dev_flux_flags
          ,gcmodel_dev_flags_trsmall
          ,gcmodel_dev_flags_maxiter
          ,gcmodel_dev_flags_numericerror
          ,gcmodel_flux_flags
          ,gcmodel_flags_region_maxarea
          ,gcmodel_flags_region_maxbadpixelfraction
          ,gcmodel_flags_region_usedfootprintarea
          ,gcmodel_flags_region_usedpsfarea
          ,gcmodel_flags_region_usedinitialellipsemin
          ,gcmodel_flags_region_usedinitialellipsemax
          ,gcmodel_flags_noshape
          ,gcmodel_flags_smallshape
          ,gcmodel_flags_nopsf
          ,gcmodel_flags_nowcs
          ,gcmodel_flags_nocalib
          ,gcmodel_flags_badcentroid
          ,gcmodel_dev_flux_flags_apcorr
          ,gcmodel_exp_flux_flags_apcorr
          ,gcmodel_flux_flags_apcorr
          ,gdeblend_psf_center_ra
          ,gdeblend_psf_center_dec
          ,gdeblend_psf_flux
          ,gdeblend_psf_mag
          ,gblendedness_old
          ,gblendedness_raw_flux
          ,gblendedness_raw_flux_child
          ,gblendedness_raw_mag_child
          ,gblendedness_raw_flux_parent
          ,gblendedness_raw_mag_parent
          ,gblendedness_abs_flux
          ,gblendedness_abs_flux_child
          ,gblendedness_abs_mag_child
          ,gblendedness_abs_flux_parent
          ,gblendedness_abs_mag_parent
          ,gblendedness_raw_shape_child_11
          ,gblendedness_raw_shape_child_22
          ,gblendedness_raw_shape_child_12
          ,gblendedness_raw_shape_parent_11
          ,gblendedness_raw_shape_parent_22
          ,gblendedness_raw_shape_parent_12
          ,gblendedness_abs_shape_child_11
          ,gblendedness_abs_shape_child_22
          ,gblendedness_abs_shape_child_12
          ,gblendedness_abs_shape_parent_11
          ,gblendedness_abs_shape_parent_22
          ,gblendedness_abs_shape_parent_12
          ,gdeblend_deblended_as_psf
          ,gdeblend_too_many_peaks
          ,gdeblend_parent_too_big
          ,gdeblend_masked
          ,gdeblend_skipped
          ,gdeblend_ramped_template
          ,gdeblend_patched_template
          ,gdeblend_has_stray_flux
          ,gblendedness_flags
          ,gblendedness_flags_nocentroid
          ,gblendedness_flags_noshape
          ,gcountinputs smallint
          ,gclassification_extendedness
          ,gflags_negative
          ,gflags_badcentroid
          ,gflags_pixel_edge
          ,gflags_pixel_interpolated_any
          ,gflags_pixel_interpolated_center
          ,gflags_pixel_saturated_any
          ,gflags_pixel_saturated_center
          ,gflags_pixel_cr_any
          ,gflags_pixel_cr_center
          ,gflags_pixel_bad
          ,gflags_pixel_suspect_any
          ,gflags_pixel_suspect_center
          ,gflags_pixel_offimage
          ,gflags_pixel_bright_object_center
          ,gflags_pixel_clipped_any
          ,gflags_pixel_bright_object_any
          ,gdetect_is_patch_inner
          ,gdetect_is_tract_inner
          ,gdetect_is_primary
          ,gcalib_psf_candidate
          ,gcalib_psf_used
          ,rflux_naive
          ,rmag_naive
          ,rflux_naive_err
          ,rmag_naive_err
          ,rflux_naive_flags
          ,rflux_sinc
          ,rmag_sinc
          ,rflux_sinc_err
          ,rmag_sinc_err
          ,rflux_sinc_flags
          ,rflux_psf
          ,rmag_psf
          ,rflux_psf_err
          ,rmag_psf_err
          ,rflux_psf_apcorr
          ,rflux_psf_apcorr_err
          ,rflux_psf_flags
          ,rflux_psf_flags_apcorr
          ,rflux_kron
          ,rmag_kron
          ,rflux_kron_err
          ,rmag_kron_err
          ,rflux_kron_radius
          ,rflux_kron_radiusforradius
          ,rflux_kron_psfradius
          ,rflux_kron_apcorr
          ,rflux_kron_apcorr_err
          ,rflux_kron_flags
          ,rflux_kron_flags_edge
          ,rflux_kron_flags_radius
          ,rflux_kron_flags_smallradius
          ,rflux_kron_flags_usedminimumradius
          ,rflux_kron_flags_usedpsfradius
          ,rflux_kron_flags_badshape
          ,rflux_kron_flags_apcorr
          ,rflux_gaussian
          ,rmag_gaussian
          ,rflux_gaussian_err
          ,rmag_gaussian_err
          ,rflux_gaussian_apcorr
          ,rflux_gaussian_apcorr_err
          ,rflux_gaussian_flags
          ,rflux_gaussian_flags_apcorr
          ,rcmodel_initial_flux
          ,rcmodel_initial_mag
          ,rcmodel_initial_flux_err
          ,rcmodel_initial_mag_err
          ,rcmodel_initial_flux_inner
          ,rcmodel_initial_mag_inner
          ,rcmodel_initial_ellipse_11
          ,rcmodel_initial_ellipse_22
          ,rcmodel_initial_ellipse_12
          ,rcmodel_initial_objective
          ,rcmodel_initial_nonlinear0
          ,rcmodel_initial_nonlinear1
          ,rcmodel_initial_nonlinear2
          ,rcmodel_initial_fixed0
          ,rcmodel_initial_fixed1
          ,rcmodel_initial_niter
          ,rcmodel_initial_time
          ,rcmodel_exp_flux
          ,rcmodel_exp_mag
          ,rcmodel_exp_flux_err
          ,rcmodel_exp_mag_err
          ,rcmodel_exp_flux_inner
          ,rcmodel_exp_mag_inner
          ,rcmodel_exp_ellipse_11
          ,rcmodel_exp_ellipse_22
          ,rcmodel_exp_ellipse_12
          ,rcmodel_exp_objective
          ,rcmodel_exp_nonlinear0
          ,rcmodel_exp_nonlinear1
          ,rcmodel_exp_nonlinear2
          ,rcmodel_exp_fixed0
          ,rcmodel_exp_fixed1
          ,rcmodel_exp_niter
          ,rcmodel_exp_time
          ,rcmodel_dev_flux
          ,rcmodel_dev_mag
          ,rcmodel_dev_flux_err
          ,rcmodel_dev_mag_err
          ,rcmodel_dev_flux_inner
          ,rcmodel_dev_mag_inner
          ,rcmodel_dev_ellipse_11
          ,rcmodel_dev_ellipse_22
          ,rcmodel_dev_ellipse_12
          ,rcmodel_dev_objective
          ,rcmodel_dev_nonlinear0
          ,rcmodel_dev_nonlinear1
          ,rcmodel_dev_nonlinear2
          ,rcmodel_dev_fixed0
          ,rcmodel_dev_fixed1
          ,rcmodel_dev_niter
          ,rcmodel_dev_time
          ,rcmodel_center_ra
          ,rcmodel_center_dec
          ,rcmodel_flux
          ,rcmodel_mag
          ,rcmodel_flux_err
          ,rcmodel_mag_err
          ,rcmodel_flux_inner
          ,rcmodel_mag_inner
          ,rcmodel_fracdev
          ,rcmodel_objective
          ,rcmodel_ellipse_11
          ,rcmodel_ellipse_22
          ,rcmodel_ellipse_12
          ,rcmodel_region_initial_ellipse_11
          ,rcmodel_region_initial_ellipse_22
          ,rcmodel_region_initial_ellipse_12
          ,rcmodel_region_final_ellipse_11
          ,rcmodel_region_final_ellipse_22
          ,rcmodel_region_final_ellipse_12
          ,rcmodel_dev_flux_apcorr
          ,rcmodel_dev_flux_apcorr_err
          ,rcmodel_exp_flux_apcorr
          ,rcmodel_exp_flux_apcorr_err
          ,rcmodel_flux_apcorr
          ,rcmodel_flux_apcorr_err
          ,rcmodel_initial_flux_flags
          ,rcmodel_initial_flags_trsmall
          ,rcmodel_initial_flags_maxiter
          ,rcmodel_initial_flags_numericerror
          ,rcmodel_exp_flux_flags
          ,rcmodel_exp_flags_trsmall
          ,rcmodel_exp_flags_maxiter
          ,rcmodel_exp_flags_numericerror
          ,rcmodel_dev_flux_flags
          ,rcmodel_dev_flags_trsmall
          ,rcmodel_dev_flags_maxiter
          ,rcmodel_dev_flags_numericerror
          ,rcmodel_flux_flags
          ,rcmodel_flags_region_maxarea
          ,rcmodel_flags_region_maxbadpixelfraction
          ,rcmodel_flags_region_usedfootprintarea
          ,rcmodel_flags_region_usedpsfarea
          ,rcmodel_flags_region_usedinitialellipsemin
          ,rcmodel_flags_region_usedinitialellipsemax
          ,rcmodel_flags_noshape
          ,rcmodel_flags_smallshape
          ,rcmodel_flags_nopsf
          ,rcmodel_flags_nowcs
          ,rcmodel_flags_nocalib
          ,rcmodel_flags_badcentroid
          ,rcmodel_dev_flux_flags_apcorr
          ,rcmodel_exp_flux_flags_apcorr
          ,rcmodel_flux_flags_apcorr
          ,rdeblend_psf_center_ra
          ,rdeblend_psf_center_dec
          ,rdeblend_psf_flux
          ,rdeblend_psf_mag
          ,rblendedness_old
          ,rblendedness_raw_flux
          ,rblendedness_raw_flux_child
          ,rblendedness_raw_mag_child
          ,rblendedness_raw_flux_parent
          ,rblendedness_raw_mag_parent
          ,rblendedness_abs_flux
          ,rblendedness_abs_flux_child
          ,rblendedness_abs_mag_child
          ,rblendedness_abs_flux_parent
          ,rblendedness_abs_mag_parent
          ,rblendedness_raw_shape_child_11
          ,rblendedness_raw_shape_child_22
          ,rblendedness_raw_shape_child_12
          ,rblendedness_raw_shape_parent_11
          ,rblendedness_raw_shape_parent_22
          ,rblendedness_raw_shape_parent_12
          ,rblendedness_abs_shape_child_11
          ,rblendedness_abs_shape_child_22
          ,rblendedness_abs_shape_child_12
          ,rblendedness_abs_shape_parent_11
          ,rblendedness_abs_shape_parent_22
          ,rblendedness_abs_shape_parent_12
          ,rdeblend_deblended_as_psf
          ,rdeblend_too_many_peaks
          ,rdeblend_parent_too_big
          ,rdeblend_masked
          ,rdeblend_skipped
          ,rdeblend_ramped_template
          ,rdeblend_patched_template
          ,rdeblend_has_stray_flux
          ,rblendedness_flags
          ,rblendedness_flags_nocentroid
          ,rblendedness_flags_noshape
          ,rcountinputs smallint
          ,rclassification_extendedness
          ,rflags_negative
          ,rflags_badcentroid
          ,rflags_pixel_edge
          ,rflags_pixel_interpolated_any
          ,rflags_pixel_interpolated_center
          ,rflags_pixel_saturated_any
          ,rflags_pixel_saturated_center
          ,rflags_pixel_cr_any
          ,rflags_pixel_cr_center
          ,rflags_pixel_bad
          ,rflags_pixel_suspect_any
          ,rflags_pixel_suspect_center
          ,rflags_pixel_offimage
          ,rflags_pixel_bright_object_center
          ,rflags_pixel_clipped_any
          ,rflags_pixel_bright_object_any
          ,rdetect_is_patch_inner
          ,rdetect_is_tract_inner
          ,rdetect_is_primary
          ,rcalib_psf_candidate
          ,rcalib_psf_used
          ,iflux_naive
          ,imag_naive
          ,iflux_naive_err
          ,imag_naive_err
          ,iflux_naive_flags
          ,iflux_sinc
          ,imag_sinc
          ,iflux_sinc_err
          ,imag_sinc_err
          ,iflux_sinc_flags
          ,iflux_psf
          ,imag_psf
          ,iflux_psf_err
          ,imag_psf_err
          ,iflux_psf_apcorr
          ,iflux_psf_apcorr_err
          ,iflux_psf_flags
          ,iflux_psf_flags_apcorr
          ,iflux_kron
          ,imag_kron
          ,iflux_kron_err
          ,imag_kron_err
          ,iflux_kron_radius
          ,iflux_kron_radiusforradius
          ,iflux_kron_psfradius
          ,iflux_kron_apcorr
          ,iflux_kron_apcorr_err
          ,iflux_kron_flags
          ,iflux_kron_flags_edge
          ,iflux_kron_flags_radius
          ,iflux_kron_flags_smallradius
          ,iflux_kron_flags_usedminimumradius
          ,iflux_kron_flags_usedpsfradius
          ,iflux_kron_flags_badshape
          ,iflux_kron_flags_apcorr
          ,iflux_gaussian
          ,imag_gaussian
          ,iflux_gaussian_err
          ,imag_gaussian_err
          ,iflux_gaussian_apcorr
          ,iflux_gaussian_apcorr_err
          ,iflux_gaussian_flags
          ,iflux_gaussian_flags_apcorr
          ,icmodel_initial_flux
          ,icmodel_initial_mag
          ,icmodel_initial_flux_err
          ,icmodel_initial_mag_err
          ,icmodel_initial_flux_inner
          ,icmodel_initial_mag_inner
          ,icmodel_initial_ellipse_11
          ,icmodel_initial_ellipse_22
          ,icmodel_initial_ellipse_12
          ,icmodel_initial_objective
          ,icmodel_initial_nonlinear0
          ,icmodel_initial_nonlinear1
          ,icmodel_initial_nonlinear2
          ,icmodel_initial_fixed0
          ,icmodel_initial_fixed1
          ,icmodel_initial_niter
          ,icmodel_initial_time
          ,icmodel_exp_flux
          ,icmodel_exp_mag
          ,icmodel_exp_flux_err
          ,icmodel_exp_mag_err
          ,icmodel_exp_flux_inner
          ,icmodel_exp_mag_inner
          ,icmodel_exp_ellipse_11
          ,icmodel_exp_ellipse_22
          ,icmodel_exp_ellipse_12
          ,icmodel_exp_objective
          ,icmodel_exp_nonlinear0
          ,icmodel_exp_nonlinear1
          ,icmodel_exp_nonlinear2
          ,icmodel_exp_fixed0
          ,icmodel_exp_fixed1
          ,icmodel_exp_niter
          ,icmodel_exp_time
          ,icmodel_dev_flux
          ,icmodel_dev_mag
          ,icmodel_dev_flux_err
          ,icmodel_dev_mag_err
          ,icmodel_dev_flux_inner
          ,icmodel_dev_mag_inner
          ,icmodel_dev_ellipse_11
          ,icmodel_dev_ellipse_22
          ,icmodel_dev_ellipse_12
          ,icmodel_dev_objective
          ,icmodel_dev_nonlinear0
          ,icmodel_dev_nonlinear1
          ,icmodel_dev_nonlinear2
          ,icmodel_dev_fixed0
          ,icmodel_dev_fixed1
          ,icmodel_dev_niter
          ,icmodel_dev_time
          ,icmodel_center_ra
          ,icmodel_center_dec
          ,icmodel_flux
          ,icmodel_mag
          ,icmodel_flux_err
          ,icmodel_mag_err
          ,icmodel_flux_inner
          ,icmodel_mag_inner
          ,icmodel_fracdev
          ,icmodel_objective
          ,icmodel_ellipse_11
          ,icmodel_ellipse_22
          ,icmodel_ellipse_12
          ,icmodel_region_initial_ellipse_11
          ,icmodel_region_initial_ellipse_22
          ,icmodel_region_initial_ellipse_12
          ,icmodel_region_final_ellipse_11
          ,icmodel_region_final_ellipse_22
          ,icmodel_region_final_ellipse_12
          ,icmodel_dev_flux_apcorr
          ,icmodel_dev_flux_apcorr_err
          ,icmodel_exp_flux_apcorr
          ,icmodel_exp_flux_apcorr_err
          ,icmodel_flux_apcorr
          ,icmodel_flux_apcorr_err
          ,icmodel_initial_flux_flags
          ,icmodel_initial_flags_trsmall
          ,icmodel_initial_flags_maxiter
          ,icmodel_initial_flags_numericerror
          ,icmodel_exp_flux_flags
          ,icmodel_exp_flags_trsmall
          ,icmodel_exp_flags_maxiter
          ,icmodel_exp_flags_numericerror
          ,icmodel_dev_flux_flags
          ,icmodel_dev_flags_trsmall
          ,icmodel_dev_flags_maxiter
          ,icmodel_dev_flags_numericerror
          ,icmodel_flux_flags
          ,icmodel_flags_region_maxarea
          ,icmodel_flags_region_maxbadpixelfraction
          ,icmodel_flags_region_usedfootprintarea
          ,icmodel_flags_region_usedpsfarea
          ,icmodel_flags_region_usedinitialellipsemin
          ,icmodel_flags_region_usedinitialellipsemax
          ,icmodel_flags_noshape
          ,icmodel_flags_smallshape
          ,icmodel_flags_nopsf
          ,icmodel_flags_nowcs
          ,icmodel_flags_nocalib
          ,icmodel_flags_badcentroid
          ,icmodel_dev_flux_flags_apcorr
          ,icmodel_exp_flux_flags_apcorr
          ,icmodel_flux_flags_apcorr
          ,ideblend_psf_center_ra
          ,ideblend_psf_center_dec
          ,ideblend_psf_flux
          ,ideblend_psf_mag
          ,iblendedness_old
          ,iblendedness_raw_flux
          ,iblendedness_raw_flux_child
          ,iblendedness_raw_mag_child
          ,iblendedness_raw_flux_parent
          ,iblendedness_raw_mag_parent
          ,iblendedness_abs_flux
          ,iblendedness_abs_flux_child
          ,iblendedness_abs_mag_child
          ,iblendedness_abs_flux_parent
          ,iblendedness_abs_mag_parent
          ,iblendedness_raw_shape_child_11
          ,iblendedness_raw_shape_child_22
          ,iblendedness_raw_shape_child_12
          ,iblendedness_raw_shape_parent_11
          ,iblendedness_raw_shape_parent_22
          ,iblendedness_raw_shape_parent_12
          ,iblendedness_abs_shape_child_11
          ,iblendedness_abs_shape_child_22
          ,iblendedness_abs_shape_child_12
          ,iblendedness_abs_shape_parent_11
          ,iblendedness_abs_shape_parent_22
          ,iblendedness_abs_shape_parent_12
          ,ideblend_deblended_as_psf
          ,ideblend_too_many_peaks
          ,ideblend_parent_too_big
          ,ideblend_masked
          ,ideblend_skipped
          ,ideblend_ramped_template
          ,ideblend_patched_template
          ,ideblend_has_stray_flux
          ,iblendedness_flags
          ,iblendedness_flags_nocentroid
          ,iblendedness_flags_noshape
          ,icountinputs smallint
          ,iclassification_extendedness
          ,iflags_negative
          ,iflags_badcentroid
          ,iflags_pixel_edge
          ,iflags_pixel_interpolated_any
          ,iflags_pixel_interpolated_center
          ,iflags_pixel_saturated_any
          ,iflags_pixel_saturated_center
          ,iflags_pixel_cr_any
          ,iflags_pixel_cr_center
          ,iflags_pixel_bad
          ,iflags_pixel_suspect_any
          ,iflags_pixel_suspect_center
          ,iflags_pixel_offimage
          ,iflags_pixel_bright_object_center
          ,iflags_pixel_clipped_any
          ,iflags_pixel_bright_object_any
          ,idetect_is_patch_inner
          ,idetect_is_tract_inner
          ,idetect_is_primary
          ,icalib_psf_candidate
          ,icalib_psf_used
          ,zflux_naive
          ,zmag_naive
          ,zflux_naive_err
          ,zmag_naive_err
          ,zflux_naive_flags
          ,zflux_sinc
          ,zmag_sinc
          ,zflux_sinc_err
          ,zmag_sinc_err
          ,zflux_sinc_flags
          ,zflux_psf
          ,zmag_psf
          ,zflux_psf_err
          ,zmag_psf_err
          ,zflux_psf_apcorr
          ,zflux_psf_apcorr_err
          ,zflux_psf_flags
          ,zflux_psf_flags_apcorr
          ,zflux_kron
          ,zmag_kron
          ,zflux_kron_err
          ,zmag_kron_err
          ,zflux_kron_radius
          ,zflux_kron_radiusforradius
          ,zflux_kron_psfradius
          ,zflux_kron_apcorr
          ,zflux_kron_apcorr_err
          ,zflux_kron_flags
          ,zflux_kron_flags_edge
          ,zflux_kron_flags_radius
          ,zflux_kron_flags_smallradius
          ,zflux_kron_flags_usedminimumradius
          ,zflux_kron_flags_usedpsfradius
          ,zflux_kron_flags_badshape
          ,zflux_kron_flags_apcorr
          ,zflux_gaussian
          ,zmag_gaussian
          ,zflux_gaussian_err
          ,zmag_gaussian_err
          ,zflux_gaussian_apcorr
          ,zflux_gaussian_apcorr_err
          ,zflux_gaussian_flags
          ,zflux_gaussian_flags_apcorr
          ,zcmodel_initial_flux
          ,zcmodel_initial_mag
          ,zcmodel_initial_flux_err
          ,zcmodel_initial_mag_err
          ,zcmodel_initial_flux_inner
          ,zcmodel_initial_mag_inner
          ,zcmodel_initial_ellipse_11
          ,zcmodel_initial_ellipse_22
          ,zcmodel_initial_ellipse_12
          ,zcmodel_initial_objective
          ,zcmodel_initial_nonlinear0
          ,zcmodel_initial_nonlinear1
          ,zcmodel_initial_nonlinear2
          ,zcmodel_initial_fixed0
          ,zcmodel_initial_fixed1
          ,zcmodel_initial_niter
          ,zcmodel_initial_time
          ,zcmodel_exp_flux
          ,zcmodel_exp_mag
          ,zcmodel_exp_flux_err
          ,zcmodel_exp_mag_err
          ,zcmodel_exp_flux_inner
          ,zcmodel_exp_mag_inner
          ,zcmodel_exp_ellipse_11
          ,zcmodel_exp_ellipse_22
          ,zcmodel_exp_ellipse_12
          ,zcmodel_exp_objective
          ,zcmodel_exp_nonlinear0
          ,zcmodel_exp_nonlinear1
          ,zcmodel_exp_nonlinear2
          ,zcmodel_exp_fixed0
          ,zcmodel_exp_fixed1
          ,zcmodel_exp_niter
          ,zcmodel_exp_time
          ,zcmodel_dev_flux
          ,zcmodel_dev_mag
          ,zcmodel_dev_flux_err
          ,zcmodel_dev_mag_err
          ,zcmodel_dev_flux_inner
          ,zcmodel_dev_mag_inner
          ,zcmodel_dev_ellipse_11
          ,zcmodel_dev_ellipse_22
          ,zcmodel_dev_ellipse_12
          ,zcmodel_dev_objective
          ,zcmodel_dev_nonlinear0
          ,zcmodel_dev_nonlinear1
          ,zcmodel_dev_nonlinear2
          ,zcmodel_dev_fixed0
          ,zcmodel_dev_fixed1
          ,zcmodel_dev_niter
          ,zcmodel_dev_time
          ,zcmodel_center_ra
          ,zcmodel_center_dec
          ,zcmodel_flux
          ,zcmodel_mag
          ,zcmodel_flux_err
          ,zcmodel_mag_err
          ,zcmodel_flux_inner
          ,zcmodel_mag_inner
          ,zcmodel_fracdev
          ,zcmodel_objective
          ,zcmodel_ellipse_11
          ,zcmodel_ellipse_22
          ,zcmodel_ellipse_12
          ,zcmodel_region_initial_ellipse_11
          ,zcmodel_region_initial_ellipse_22
          ,zcmodel_region_initial_ellipse_12
          ,zcmodel_region_final_ellipse_11
          ,zcmodel_region_final_ellipse_22
          ,zcmodel_region_final_ellipse_12
          ,zcmodel_dev_flux_apcorr
          ,zcmodel_dev_flux_apcorr_err
          ,zcmodel_exp_flux_apcorr
          ,zcmodel_exp_flux_apcorr_err
          ,zcmodel_flux_apcorr
          ,zcmodel_flux_apcorr_err
          ,zcmodel_initial_flux_flags
          ,zcmodel_initial_flags_trsmall
          ,zcmodel_initial_flags_maxiter
          ,zcmodel_initial_flags_numericerror
          ,zcmodel_exp_flux_flags
          ,zcmodel_exp_flags_trsmall
          ,zcmodel_exp_flags_maxiter
          ,zcmodel_exp_flags_numericerror
          ,zcmodel_dev_flux_flags
          ,zcmodel_dev_flags_trsmall
          ,zcmodel_dev_flags_maxiter
          ,zcmodel_dev_flags_numericerror
          ,zcmodel_flux_flags
          ,zcmodel_flags_region_maxarea
          ,zcmodel_flags_region_maxbadpixelfraction
          ,zcmodel_flags_region_usedfootprintarea
          ,zcmodel_flags_region_usedpsfarea
          ,zcmodel_flags_region_usedinitialellipsemin
          ,zcmodel_flags_region_usedinitialellipsemax
          ,zcmodel_flags_noshape
          ,zcmodel_flags_smallshape
          ,zcmodel_flags_nopsf
          ,zcmodel_flags_nowcs
          ,zcmodel_flags_nocalib
          ,zcmodel_flags_badcentroid
          ,zcmodel_dev_flux_flags_apcorr
          ,zcmodel_exp_flux_flags_apcorr
          ,zcmodel_flux_flags_apcorr
          ,zdeblend_psf_center_ra
          ,zdeblend_psf_center_dec
          ,zdeblend_psf_flux
          ,zdeblend_psf_mag
          ,zblendedness_old
          ,zblendedness_raw_flux
          ,zblendedness_raw_flux_child
          ,zblendedness_raw_mag_child
          ,zblendedness_raw_flux_parent
          ,zblendedness_raw_mag_parent
          ,zblendedness_abs_flux
          ,zblendedness_abs_flux_child
          ,zblendedness_abs_mag_child
          ,zblendedness_abs_flux_parent
          ,zblendedness_abs_mag_parent
          ,zblendedness_raw_shape_child_11
          ,zblendedness_raw_shape_child_22
          ,zblendedness_raw_shape_child_12
          ,zblendedness_raw_shape_parent_11
          ,zblendedness_raw_shape_parent_22
          ,zblendedness_raw_shape_parent_12
          ,zblendedness_abs_shape_child_11
          ,zblendedness_abs_shape_child_22
          ,zblendedness_abs_shape_child_12
          ,zblendedness_abs_shape_parent_11
          ,zblendedness_abs_shape_parent_22
          ,zblendedness_abs_shape_parent_12
          ,zdeblend_deblended_as_psf
          ,zdeblend_too_many_peaks
          ,zdeblend_parent_too_big
          ,zdeblend_masked
          ,zdeblend_skipped
          ,zdeblend_ramped_template
          ,zdeblend_patched_template
          ,zdeblend_has_stray_flux
          ,zblendedness_flags
          ,zblendedness_flags_nocentroid
          ,zblendedness_flags_noshape
          ,zcountinputs smallint
          ,zclassification_extendedness
          ,zflags_negative
          ,zflags_badcentroid
          ,zflags_pixel_edge
          ,zflags_pixel_interpolated_any
          ,zflags_pixel_interpolated_center
          ,zflags_pixel_saturated_any
          ,zflags_pixel_saturated_center
          ,zflags_pixel_cr_any
          ,zflags_pixel_cr_center
          ,zflags_pixel_bad
          ,zflags_pixel_suspect_any
          ,zflags_pixel_suspect_center
          ,zflags_pixel_offimage
          ,zflags_pixel_bright_object_center
          ,zflags_pixel_clipped_any
          ,zflags_pixel_bright_object_any
          ,zdetect_is_patch_inner
          ,zdetect_is_tract_inner
          ,zdetect_is_primary
          ,zcalib_psf_candidate
          ,zcalib_psf_used
          ,yflux_naive
          ,ymag_naive
          ,yflux_naive_err
          ,ymag_naive_err
          ,yflux_naive_flags
          ,yflux_sinc
          ,ymag_sinc
          ,yflux_sinc_err
          ,ymag_sinc_err
          ,yflux_sinc_flags
          ,yflux_psf
          ,ymag_psf
          ,yflux_psf_err
          ,ymag_psf_err
          ,yflux_psf_apcorr
          ,yflux_psf_apcorr_err
          ,yflux_psf_flags
          ,yflux_psf_flags_apcorr
          ,yflux_kron
          ,ymag_kron
          ,yflux_kron_err
          ,ymag_kron_err
          ,yflux_kron_radius
          ,yflux_kron_radiusforradius
          ,yflux_kron_psfradius
          ,yflux_kron_apcorr
          ,yflux_kron_apcorr_err
          ,yflux_kron_flags
          ,yflux_kron_flags_edge
          ,yflux_kron_flags_radius
          ,yflux_kron_flags_smallradius
          ,yflux_kron_flags_usedminimumradius
          ,yflux_kron_flags_usedpsfradius
          ,yflux_kron_flags_badshape
          ,yflux_kron_flags_apcorr
          ,yflux_gaussian
          ,ymag_gaussian
          ,yflux_gaussian_err
          ,ymag_gaussian_err
          ,yflux_gaussian_apcorr
          ,yflux_gaussian_apcorr_err
          ,yflux_gaussian_flags
          ,yflux_gaussian_flags_apcorr
          ,ycmodel_initial_flux
          ,ycmodel_initial_mag
          ,ycmodel_initial_flux_err
          ,ycmodel_initial_mag_err
          ,ycmodel_initial_flux_inner
          ,ycmodel_initial_mag_inner
          ,ycmodel_initial_ellipse_11
          ,ycmodel_initial_ellipse_22
          ,ycmodel_initial_ellipse_12
          ,ycmodel_initial_objective
          ,ycmodel_initial_nonlinear0
          ,ycmodel_initial_nonlinear1
          ,ycmodel_initial_nonlinear2
          ,ycmodel_initial_fixed0
          ,ycmodel_initial_fixed1
          ,ycmodel_initial_niter
          ,ycmodel_initial_time
          ,ycmodel_exp_flux
          ,ycmodel_exp_mag
          ,ycmodel_exp_flux_err
          ,ycmodel_exp_mag_err
          ,ycmodel_exp_flux_inner
          ,ycmodel_exp_mag_inner
          ,ycmodel_exp_ellipse_11
          ,ycmodel_exp_ellipse_22
          ,ycmodel_exp_ellipse_12
          ,ycmodel_exp_objective
          ,ycmodel_exp_nonlinear0
          ,ycmodel_exp_nonlinear1
          ,ycmodel_exp_nonlinear2
          ,ycmodel_exp_fixed0
          ,ycmodel_exp_fixed1
          ,ycmodel_exp_niter
          ,ycmodel_exp_time
          ,ycmodel_dev_flux
          ,ycmodel_dev_mag
          ,ycmodel_dev_flux_err
          ,ycmodel_dev_mag_err
          ,ycmodel_dev_flux_inner
          ,ycmodel_dev_mag_inner
          ,ycmodel_dev_ellipse_11
          ,ycmodel_dev_ellipse_22
          ,ycmodel_dev_ellipse_12
          ,ycmodel_dev_objective
          ,ycmodel_dev_nonlinear0
          ,ycmodel_dev_nonlinear1
          ,ycmodel_dev_nonlinear2
          ,ycmodel_dev_fixed0
          ,ycmodel_dev_fixed1
          ,ycmodel_dev_niter
          ,ycmodel_dev_time
          ,ycmodel_center_ra
          ,ycmodel_center_dec
          ,ycmodel_flux
          ,ycmodel_mag
          ,ycmodel_flux_err
          ,ycmodel_mag_err
          ,ycmodel_flux_inner
          ,ycmodel_mag_inner
          ,ycmodel_fracdev
          ,ycmodel_objective
          ,ycmodel_ellipse_11
          ,ycmodel_ellipse_22
          ,ycmodel_ellipse_12
          ,ycmodel_region_initial_ellipse_11
          ,ycmodel_region_initial_ellipse_22
          ,ycmodel_region_initial_ellipse_12
          ,ycmodel_region_final_ellipse_11
          ,ycmodel_region_final_ellipse_22
          ,ycmodel_region_final_ellipse_12
          ,ycmodel_dev_flux_apcorr
          ,ycmodel_dev_flux_apcorr_err
          ,ycmodel_exp_flux_apcorr
          ,ycmodel_exp_flux_apcorr_err
          ,ycmodel_flux_apcorr
          ,ycmodel_flux_apcorr_err
          ,ycmodel_initial_flux_flags
          ,ycmodel_initial_flags_trsmall
          ,ycmodel_initial_flags_maxiter
          ,ycmodel_initial_flags_numericerror
          ,ycmodel_exp_flux_flags
          ,ycmodel_exp_flags_trsmall
          ,ycmodel_exp_flags_maxiter
          ,ycmodel_exp_flags_numericerror
          ,ycmodel_dev_flux_flags
          ,ycmodel_dev_flags_trsmall
          ,ycmodel_dev_flags_maxiter
          ,ycmodel_dev_flags_numericerror
          ,ycmodel_flux_flags
          ,ycmodel_flags_region_maxarea
          ,ycmodel_flags_region_maxbadpixelfraction
          ,ycmodel_flags_region_usedfootprintarea
          ,ycmodel_flags_region_usedpsfarea
          ,ycmodel_flags_region_usedinitialellipsemin
          ,ycmodel_flags_region_usedinitialellipsemax
          ,ycmodel_flags_noshape
          ,ycmodel_flags_smallshape
          ,ycmodel_flags_nopsf
          ,ycmodel_flags_nowcs
          ,ycmodel_flags_nocalib
          ,ycmodel_flags_badcentroid
          ,ycmodel_dev_flux_flags_apcorr
          ,ycmodel_exp_flux_flags_apcorr
          ,ycmodel_flux_flags_apcorr
          ,ydeblend_psf_center_ra
          ,ydeblend_psf_center_dec
          ,ydeblend_psf_flux
          ,ydeblend_psf_mag
          ,yblendedness_old
          ,yblendedness_raw_flux
          ,yblendedness_raw_flux_child
          ,yblendedness_raw_mag_child
          ,yblendedness_raw_flux_parent
          ,yblendedness_raw_mag_parent
          ,yblendedness_abs_flux
          ,yblendedness_abs_flux_child
          ,yblendedness_abs_mag_child
          ,yblendedness_abs_flux_parent
          ,yblendedness_abs_mag_parent
          ,yblendedness_raw_shape_child_11
          ,yblendedness_raw_shape_child_22
          ,yblendedness_raw_shape_child_12
          ,yblendedness_raw_shape_parent_11
          ,yblendedness_raw_shape_parent_22
          ,yblendedness_raw_shape_parent_12
          ,yblendedness_abs_shape_child_11
          ,yblendedness_abs_shape_child_22
          ,yblendedness_abs_shape_child_12
          ,yblendedness_abs_shape_parent_11
          ,yblendedness_abs_shape_parent_22
          ,yblendedness_abs_shape_parent_12
          ,ydeblend_deblended_as_psf
          ,ydeblend_too_many_peaks
          ,ydeblend_parent_too_big
          ,ydeblend_masked
          ,ydeblend_skipped
          ,ydeblend_ramped_template
          ,ydeblend_patched_template
          ,ydeblend_has_stray_flux
          ,yblendedness_flags
          ,yblendedness_flags_nocentroid
          ,yblendedness_flags_noshape
          ,ycountinputs smallint
          ,yclassification_extendedness
          ,yflags_negative
          ,yflags_badcentroid
          ,yflags_pixel_edge
          ,yflags_pixel_interpolated_any
          ,yflags_pixel_interpolated_center
          ,yflags_pixel_saturated_any
          ,yflags_pixel_saturated_center
          ,yflags_pixel_cr_any
          ,yflags_pixel_cr_center
          ,yflags_pixel_bad
          ,yflags_pixel_suspect_any
          ,yflags_pixel_suspect_center
          ,yflags_pixel_offimage
          ,yflags_pixel_bright_object_center
          ,yflags_pixel_clipped_any
          ,yflags_pixel_bright_object_any
          ,ydetect_is_patch_inner
          ,ydetect_is_tract_inner
          ,ydetect_is_primary
          ,ycalib_psf_candidate
          ,ycalib_psf_used
        )
      }
  }

  def photoz()={
    sc.textFile("hdfs://user/matsumoto/sample_pdr1_wide.photoz_demp").
      map { lines => val elms = lines.split(",")
        val object_id = elms().toInt
        val photoz_mean = elms().toFloat
        val photoz_mode = elms().toFloat
        val photoz_median = elms().toFloat
        val photoz_best = elms().toFloat
        val photoz_mc = elms().toFloat
        val photoz_conf_mean = elms().toFloat
        val photoz_conf_mode = elms().toFloat
        val photoz_conf_median = elms().toFloat
        val photoz_conf_best = elms().toFloat
        val photoz_risk_mean = elms().toFloat
        val photoz_risk_mode = elms().toFloat
        val photoz_risk_median = elms().toFloat
        val photoz_risk_best = elms().toFloat
        val photoz_std_mean = elms().toFloat
        val photoz_std_mode = elms().toFloat
        val photoz_std_median = elms().toFloat
        val photoz_std_best = elms().toFloat
        val photoz_err68_min = elms().toFloat
        val photoz_err68_max = elms().toFloat
        val photoz_err95_min = elms().toFloat
        val photoz_err95_max = elms().toFloat
      
        (
          object_id
          ,photoz_mean, photoz_mode, photoz_median, photoz_best, photoz_mc
          ,photoz_conf_mean, photoz_conf_mode, photoz_conf_median, photoz_conf_best
          ,photoz_risk_mean, photoz_risk_mode, photoz_risk_median, photoz_risk_best
          ,photoz_std_mean, photoz_std_mode, photoz_std_median, photoz_std_best
          ,photoz_err68_min, photoz_err68_max, photoz_err95_min, photoz_err95_max
        )
      }    
  }
}
