use pdr1_hive;
drop table if exists pdr1_wide_meas;
create EXTERNAL TABLE pdr1_wide_meas(
object_id bigint
,gra double
,gdec double
,gcoord string
,rra double
,rdec double
,rcoord string
,ira double
,idec double
,icoord string
,zra double
,zdec double
,zcoord string
,yra double
,ydec double
,ycoord string
,skymap_id int
,tract int
,patch int
,patch_s string
,parent_id bigint
,deblend_nchild int
,merge_footprint_i2 string
,merge_footprint_i string
,merge_footprint_r string
,merge_footprint_z string
,merge_footprint_y string
,merge_footprint_g string
,merge_footprint_n921 string
,merge_footprint_n816 string
,merge_footprint_n1010 string
,merge_footprint_n387 string
,merge_footprint_n515 string
,merge_footprint_sky string
,merge_peak_i2 string
,merge_peak_i string
,merge_peak_r string
,merge_peak_z string
,merge_peak_y string
,merge_peak_g string
,merge_peak_n921 string
,merge_peak_n816 string
,merge_peak_n1010 string
,merge_peak_n387 string
,merge_peak_n515 string
,merge_peak_sky string
,gflux_naive double
,gmag_naive float
,gflux_naive_err double
,gmag_naive_err float
,gflux_naive_flags string
,gflux_sinc double
,gmag_sinc float
,gflux_sinc_err double
,gmag_sinc_err float
,gflux_sinc_flags string
,gflux_psf double
,gmag_psf float
,gflux_psf_err double
,gmag_psf_err float
,gflux_psf_apcorr float
,gflux_psf_apcorr_err float
,gflux_psf_flags string
,gflux_psf_flags_apcorr string
,gflux_kron double
,gmag_kron float
,gflux_kron_err double
,gmag_kron_err float
,gflux_kron_radius float
,gflux_kron_radiusforradius float
,gflux_kron_psfradius float
,gflux_kron_apcorr float
,gflux_kron_apcorr_err float
,gflux_kron_flags string
,gflux_kron_flags_edge string
,gflux_kron_flags_radius string
,gflux_kron_flags_smallradius string
,gflux_kron_flags_usedminimumradius string
,gflux_kron_flags_usedpsfradius string
,gflux_kron_flags_badshape string
,gflux_kron_flags_apcorr string
,gflux_gaussian double
,gmag_gaussian float
,gflux_gaussian_err double
,gmag_gaussian_err float
,gflux_gaussian_apcorr float
,gflux_gaussian_apcorr_err float
,gflux_gaussian_flags string
,gflux_gaussian_flags_apcorr string
,gcmodel_initial_flux double
,gcmodel_initial_mag float
,gcmodel_initial_flux_err double
,gcmodel_initial_mag_err float
,gcmodel_initial_flux_inner double
,gcmodel_initial_mag_inner float
,gcmodel_initial_ellipse_11 float
,gcmodel_initial_ellipse_22 float
,gcmodel_initial_ellipse_12 float
,gcmodel_initial_objective float
,gcmodel_initial_nonlinear0 float
,gcmodel_initial_nonlinear1 float
,gcmodel_initial_nonlinear2 float
,gcmodel_initial_fixed0 float
,gcmodel_initial_fixed1 float
,gcmodel_initial_niter int
,gcmodel_initial_time float
,gcmodel_exp_flux double
,gcmodel_exp_mag float
,gcmodel_exp_flux_err double
,gcmodel_exp_mag_err float
,gcmodel_exp_flux_inner double
,gcmodel_exp_mag_inner float
,gcmodel_exp_ellipse_11 float
,gcmodel_exp_ellipse_22 float
,gcmodel_exp_ellipse_12 float
,gcmodel_exp_objective float
,gcmodel_exp_nonlinear0 float
,gcmodel_exp_nonlinear1 float
,gcmodel_exp_nonlinear2 float
,gcmodel_exp_fixed0 float
,gcmodel_exp_fixed1 float
,gcmodel_exp_niter int
,gcmodel_exp_time float
,gcmodel_dev_flux double
,gcmodel_dev_mag float
,gcmodel_dev_flux_err double
,gcmodel_dev_mag_err float
,gcmodel_dev_flux_inner double
,gcmodel_dev_mag_inner float
,gcmodel_dev_ellipse_11 float
,gcmodel_dev_ellipse_22 float
,gcmodel_dev_ellipse_12 float
,gcmodel_dev_objective float
,gcmodel_dev_nonlinear0 float
,gcmodel_dev_nonlinear1 float
,gcmodel_dev_nonlinear2 float
,gcmodel_dev_fixed0 float
,gcmodel_dev_fixed1 float
,gcmodel_dev_niter int
,gcmodel_dev_time float
,gcmodel_center_ra double
,gcmodel_center_dec double
,gcmodel_flux double
,gcmodel_mag float
,gcmodel_flux_err double
,gcmodel_mag_err float
,gcmodel_flux_inner double
,gcmodel_mag_inner float
,gcmodel_fracdev float
,gcmodel_objective float
,gcmodel_ellipse_11 float
,gcmodel_ellipse_22 float
,gcmodel_ellipse_12 float
,gcmodel_region_initial_ellipse_11 float
,gcmodel_region_initial_ellipse_22 float
,gcmodel_region_initial_ellipse_12 float
,gcmodel_region_final_ellipse_11 float
,gcmodel_region_final_ellipse_22 float
,gcmodel_region_final_ellipse_12 float
,gcmodel_dev_flux_apcorr float
,gcmodel_dev_flux_apcorr_err float
,gcmodel_exp_flux_apcorr float
,gcmodel_exp_flux_apcorr_err float
,gcmodel_flux_apcorr float
,gcmodel_flux_apcorr_err float
,gcmodel_initial_flux_flags string
,gcmodel_initial_flags_trsmall string
,gcmodel_initial_flags_maxiter string
,gcmodel_initial_flags_numericerror string
,gcmodel_exp_flux_flags string
,gcmodel_exp_flags_trsmall string
,gcmodel_exp_flags_maxiter string
,gcmodel_exp_flags_numericerror string
,gcmodel_dev_flux_flags string
,gcmodel_dev_flags_trsmall string
,gcmodel_dev_flags_maxiter string
,gcmodel_dev_flags_numericerror string
,gcmodel_flux_flags string
,gcmodel_flags_region_maxarea string
,gcmodel_flags_region_maxbadpixelfraction string
,gcmodel_flags_region_usedfootprintarea string
,gcmodel_flags_region_usedpsfarea string
,gcmodel_flags_region_usedinitialellipsemin string
,gcmodel_flags_region_usedinitialellipsemax string
,gcmodel_flags_noshape string
,gcmodel_flags_smallshape string
,gcmodel_flags_nopsf string
,gcmodel_flags_nowcs string
,gcmodel_flags_nocalib string
,gcmodel_flags_badcentroid string
,gcmodel_dev_flux_flags_apcorr string
,gcmodel_exp_flux_flags_apcorr string
,gcmodel_flux_flags_apcorr string
,gdeblend_psf_center_ra double
,gdeblend_psf_center_dec double
,gdeblend_psf_flux double
,gdeblend_psf_mag float
,gblendedness_old float
,gblendedness_raw_flux float
,gblendedness_raw_flux_child double
,gblendedness_raw_mag_child float
,gblendedness_raw_flux_parent double
,gblendedness_raw_mag_parent float
,gblendedness_abs_flux float
,gblendedness_abs_flux_child double
,gblendedness_abs_mag_child float
,gblendedness_abs_flux_parent double
,gblendedness_abs_mag_parent float
,gblendedness_raw_shape_child_11 float
,gblendedness_raw_shape_child_22 float
,gblendedness_raw_shape_child_12 float
,gblendedness_raw_shape_parent_11 float
,gblendedness_raw_shape_parent_22 float
,gblendedness_raw_shape_parent_12 float
,gblendedness_abs_shape_child_11 float
,gblendedness_abs_shape_child_22 float
,gblendedness_abs_shape_child_12 float
,gblendedness_abs_shape_parent_11 float
,gblendedness_abs_shape_parent_22 float
,gblendedness_abs_shape_parent_12 float
,gdeblend_deblended_as_psf string
,gdeblend_too_many_peaks string
,gdeblend_parent_too_big string
,gdeblend_masked string
,gdeblend_skipped string
,gdeblend_ramped_template string
,gdeblend_patched_template string
,gdeblend_has_stray_flux string
,gblendedness_flags string
,gblendedness_flags_nocentroid string
,gblendedness_flags_noshape string
,gcountinputs smallint
,gclassification_extendedness float
,gflags_negative string
,gflags_badcentroid string
,gflags_pixel_edge string
,gflags_pixel_interpolated_any string
,gflags_pixel_interpolated_center string
,gflags_pixel_saturated_any string
,gflags_pixel_saturated_center string
,gflags_pixel_cr_any string
,gflags_pixel_cr_center string
,gflags_pixel_bad string
,gflags_pixel_suspect_any string
,gflags_pixel_suspect_center string
,gflags_pixel_offimage string
,gflags_pixel_bright_object_center string
,gflags_pixel_clipped_any string
,gflags_pixel_bright_object_any string
,gdetect_is_patch_inner string
,gdetect_is_tract_inner string
,gdetect_is_primary string
,gcalib_psf_candidate string
,gcalib_psf_used string
,rflux_naive double
,rmag_naive float
,rflux_naive_err double
,rmag_naive_err float
,rflux_naive_flags string
,rflux_sinc double
,rmag_sinc float
,rflux_sinc_err double
,rmag_sinc_err float
,rflux_sinc_flags string
,rflux_psf double
,rmag_psf float
,rflux_psf_err double
,rmag_psf_err float
,rflux_psf_apcorr float
,rflux_psf_apcorr_err float
,rflux_psf_flags string
,rflux_psf_flags_apcorr string
,rflux_kron double
,rmag_kron float
,rflux_kron_err double
,rmag_kron_err float
,rflux_kron_radius float
,rflux_kron_radiusforradius float
,rflux_kron_psfradius float
,rflux_kron_apcorr float
,rflux_kron_apcorr_err float
,rflux_kron_flags string
,rflux_kron_flags_edge string
,rflux_kron_flags_radius string
,rflux_kron_flags_smallradius string
,rflux_kron_flags_usedminimumradius string
,rflux_kron_flags_usedpsfradius string
,rflux_kron_flags_badshape string
,rflux_kron_flags_apcorr string
,rflux_gaussian double
,rmag_gaussian float
,rflux_gaussian_err double
,rmag_gaussian_err float
,rflux_gaussian_apcorr float
,rflux_gaussian_apcorr_err float
,rflux_gaussian_flags string
,rflux_gaussian_flags_apcorr string
,rcmodel_initial_flux double
,rcmodel_initial_mag float
,rcmodel_initial_flux_err double
,rcmodel_initial_mag_err float
,rcmodel_initial_flux_inner double
,rcmodel_initial_mag_inner float
,rcmodel_initial_ellipse_11 float
,rcmodel_initial_ellipse_22 float
,rcmodel_initial_ellipse_12 float
,rcmodel_initial_objective float
,rcmodel_initial_nonlinear0 float
,rcmodel_initial_nonlinear1 float
,rcmodel_initial_nonlinear2 float
,rcmodel_initial_fixed0 float
,rcmodel_initial_fixed1 float
,rcmodel_initial_niter int
,rcmodel_initial_time float
,rcmodel_exp_flux double
,rcmodel_exp_mag float
,rcmodel_exp_flux_err double
,rcmodel_exp_mag_err float
,rcmodel_exp_flux_inner double
,rcmodel_exp_mag_inner float
,rcmodel_exp_ellipse_11 float
,rcmodel_exp_ellipse_22 float
,rcmodel_exp_ellipse_12 float
,rcmodel_exp_objective float
,rcmodel_exp_nonlinear0 float
,rcmodel_exp_nonlinear1 float
,rcmodel_exp_nonlinear2 float
,rcmodel_exp_fixed0 float
,rcmodel_exp_fixed1 float
,rcmodel_exp_niter int
,rcmodel_exp_time float
,rcmodel_dev_flux double
,rcmodel_dev_mag float
,rcmodel_dev_flux_err double
,rcmodel_dev_mag_err float
,rcmodel_dev_flux_inner double
,rcmodel_dev_mag_inner float
,rcmodel_dev_ellipse_11 float
,rcmodel_dev_ellipse_22 float
,rcmodel_dev_ellipse_12 float
,rcmodel_dev_objective float
,rcmodel_dev_nonlinear0 float
,rcmodel_dev_nonlinear1 float
,rcmodel_dev_nonlinear2 float
,rcmodel_dev_fixed0 float
,rcmodel_dev_fixed1 float
,rcmodel_dev_niter int
,rcmodel_dev_time float
,rcmodel_center_ra double
,rcmodel_center_dec double
,rcmodel_flux double
,rcmodel_mag float
,rcmodel_flux_err double
,rcmodel_mag_err float
,rcmodel_flux_inner double
,rcmodel_mag_inner float
,rcmodel_fracdev float
,rcmodel_objective float
,rcmodel_ellipse_11 float
,rcmodel_ellipse_22 float
,rcmodel_ellipse_12 float
,rcmodel_region_initial_ellipse_11 float
,rcmodel_region_initial_ellipse_22 float
,rcmodel_region_initial_ellipse_12 float
,rcmodel_region_final_ellipse_11 float
,rcmodel_region_final_ellipse_22 float
,rcmodel_region_final_ellipse_12 float
,rcmodel_dev_flux_apcorr float
,rcmodel_dev_flux_apcorr_err float
,rcmodel_exp_flux_apcorr float
,rcmodel_exp_flux_apcorr_err float
,rcmodel_flux_apcorr float
,rcmodel_flux_apcorr_err float
,rcmodel_initial_flux_flags string
,rcmodel_initial_flags_trsmall string
,rcmodel_initial_flags_maxiter string
,rcmodel_initial_flags_numericerror string
,rcmodel_exp_flux_flags string
,rcmodel_exp_flags_trsmall string
,rcmodel_exp_flags_maxiter string
,rcmodel_exp_flags_numericerror string
,rcmodel_dev_flux_flags string
,rcmodel_dev_flags_trsmall string
,rcmodel_dev_flags_maxiter string
,rcmodel_dev_flags_numericerror string
,rcmodel_flux_flags string
,rcmodel_flags_region_maxarea string
,rcmodel_flags_region_maxbadpixelfraction string
,rcmodel_flags_region_usedfootprintarea string
,rcmodel_flags_region_usedpsfarea string
,rcmodel_flags_region_usedinitialellipsemin string
,rcmodel_flags_region_usedinitialellipsemax string
,rcmodel_flags_noshape string
,rcmodel_flags_smallshape string
,rcmodel_flags_nopsf string
,rcmodel_flags_nowcs string
,rcmodel_flags_nocalib string
,rcmodel_flags_badcentroid string
,rcmodel_dev_flux_flags_apcorr string
,rcmodel_exp_flux_flags_apcorr string
,rcmodel_flux_flags_apcorr string
,rdeblend_psf_center_ra double
,rdeblend_psf_center_dec double
,rdeblend_psf_flux double
,rdeblend_psf_mag float
,rblendedness_old float
,rblendedness_raw_flux float
,rblendedness_raw_flux_child double
,rblendedness_raw_mag_child float
,rblendedness_raw_flux_parent double
,rblendedness_raw_mag_parent float
,rblendedness_abs_flux float
,rblendedness_abs_flux_child double
,rblendedness_abs_mag_child float
,rblendedness_abs_flux_parent double
,rblendedness_abs_mag_parent float
,rblendedness_raw_shape_child_11 float
,rblendedness_raw_shape_child_22 float
,rblendedness_raw_shape_child_12 float
,rblendedness_raw_shape_parent_11 float
,rblendedness_raw_shape_parent_22 float
,rblendedness_raw_shape_parent_12 float
,rblendedness_abs_shape_child_11 float
,rblendedness_abs_shape_child_22 float
,rblendedness_abs_shape_child_12 float
,rblendedness_abs_shape_parent_11 float
,rblendedness_abs_shape_parent_22 float
,rblendedness_abs_shape_parent_12 float
,rdeblend_deblended_as_psf string
,rdeblend_too_many_peaks string
,rdeblend_parent_too_big string
,rdeblend_masked string
,rdeblend_skipped string
,rdeblend_ramped_template string
,rdeblend_patched_template string
,rdeblend_has_stray_flux string
,rblendedness_flags string
,rblendedness_flags_nocentroid string
,rblendedness_flags_noshape string
,rcountinputs smallint
,rclassification_extendedness float
,rflags_negative string
,rflags_badcentroid string
,rflags_pixel_edge string
,rflags_pixel_interpolated_any string
,rflags_pixel_interpolated_center string
,rflags_pixel_saturated_any string
,rflags_pixel_saturated_center string
,rflags_pixel_cr_any string
,rflags_pixel_cr_center string
,rflags_pixel_bad string
,rflags_pixel_suspect_any string
,rflags_pixel_suspect_center string
,rflags_pixel_offimage string
,rflags_pixel_bright_object_center string
,rflags_pixel_clipped_any string
,rflags_pixel_bright_object_any string
,rdetect_is_patch_inner string
,rdetect_is_tract_inner string
,rdetect_is_primary string
,rcalib_psf_candidate string
,rcalib_psf_used string
,iflux_naive double
,imag_naive float
,iflux_naive_err double
,imag_naive_err float
,iflux_naive_flags string
,iflux_sinc double
,imag_sinc float
,iflux_sinc_err double
,imag_sinc_err float
,iflux_sinc_flags string
,iflux_psf double
,imag_psf float
,iflux_psf_err double
,imag_psf_err float
,iflux_psf_apcorr float
,iflux_psf_apcorr_err float
,iflux_psf_flags string
,iflux_psf_flags_apcorr string
,iflux_kron double
,imag_kron float
,iflux_kron_err double
,imag_kron_err float
,iflux_kron_radius float
,iflux_kron_radiusforradius float
,iflux_kron_psfradius float
,iflux_kron_apcorr float
,iflux_kron_apcorr_err float
,iflux_kron_flags string
,iflux_kron_flags_edge string
,iflux_kron_flags_radius string
,iflux_kron_flags_smallradius string
,iflux_kron_flags_usedminimumradius string
,iflux_kron_flags_usedpsfradius string
,iflux_kron_flags_badshape string
,iflux_kron_flags_apcorr string
,iflux_gaussian double
,imag_gaussian float
,iflux_gaussian_err double
,imag_gaussian_err float
,iflux_gaussian_apcorr float
,iflux_gaussian_apcorr_err float
,iflux_gaussian_flags string
,iflux_gaussian_flags_apcorr string
,icmodel_initial_flux double
,icmodel_initial_mag float
,icmodel_initial_flux_err double
,icmodel_initial_mag_err float
,icmodel_initial_flux_inner double
,icmodel_initial_mag_inner float
,icmodel_initial_ellipse_11 float
,icmodel_initial_ellipse_22 float
,icmodel_initial_ellipse_12 float
,icmodel_initial_objective float
,icmodel_initial_nonlinear0 float
,icmodel_initial_nonlinear1 float
,icmodel_initial_nonlinear2 float
,icmodel_initial_fixed0 float
,icmodel_initial_fixed1 float
,icmodel_initial_niter int
,icmodel_initial_time float
,icmodel_exp_flux double
,icmodel_exp_mag float
,icmodel_exp_flux_err double
,icmodel_exp_mag_err float
,icmodel_exp_flux_inner double
,icmodel_exp_mag_inner float
,icmodel_exp_ellipse_11 float
,icmodel_exp_ellipse_22 float
,icmodel_exp_ellipse_12 float
,icmodel_exp_objective float
,icmodel_exp_nonlinear0 float
,icmodel_exp_nonlinear1 float
,icmodel_exp_nonlinear2 float
,icmodel_exp_fixed0 float
,icmodel_exp_fixed1 float
,icmodel_exp_niter int
,icmodel_exp_time float
,icmodel_dev_flux double
,icmodel_dev_mag float
,icmodel_dev_flux_err double
,icmodel_dev_mag_err float
,icmodel_dev_flux_inner double
,icmodel_dev_mag_inner float
,icmodel_dev_ellipse_11 float
,icmodel_dev_ellipse_22 float
,icmodel_dev_ellipse_12 float
,icmodel_dev_objective float
,icmodel_dev_nonlinear0 float
,icmodel_dev_nonlinear1 float
,icmodel_dev_nonlinear2 float
,icmodel_dev_fixed0 float
,icmodel_dev_fixed1 float
,icmodel_dev_niter int
,icmodel_dev_time float
,icmodel_center_ra double
,icmodel_center_dec double
,icmodel_flux double
,icmodel_mag float
,icmodel_flux_err double
,icmodel_mag_err float
,icmodel_flux_inner double
,icmodel_mag_inner float
,icmodel_fracdev float
,icmodel_objective float
,icmodel_ellipse_11 float
,icmodel_ellipse_22 float
,icmodel_ellipse_12 float
,icmodel_region_initial_ellipse_11 float
,icmodel_region_initial_ellipse_22 float
,icmodel_region_initial_ellipse_12 float
,icmodel_region_final_ellipse_11 float
,icmodel_region_final_ellipse_22 float
,icmodel_region_final_ellipse_12 float
,icmodel_dev_flux_apcorr float
,icmodel_dev_flux_apcorr_err float
,icmodel_exp_flux_apcorr float
,icmodel_exp_flux_apcorr_err float
,icmodel_flux_apcorr float
,icmodel_flux_apcorr_err float
,icmodel_initial_flux_flags string
,icmodel_initial_flags_trsmall string
,icmodel_initial_flags_maxiter string
,icmodel_initial_flags_numericerror string
,icmodel_exp_flux_flags string
,icmodel_exp_flags_trsmall string
,icmodel_exp_flags_maxiter string
,icmodel_exp_flags_numericerror string
,icmodel_dev_flux_flags string
,icmodel_dev_flags_trsmall string
,icmodel_dev_flags_maxiter string
,icmodel_dev_flags_numericerror string
,icmodel_flux_flags string
,icmodel_flags_region_maxarea string
,icmodel_flags_region_maxbadpixelfraction string
,icmodel_flags_region_usedfootprintarea string
,icmodel_flags_region_usedpsfarea string
,icmodel_flags_region_usedinitialellipsemin string
,icmodel_flags_region_usedinitialellipsemax string
,icmodel_flags_noshape string
,icmodel_flags_smallshape string
,icmodel_flags_nopsf string
,icmodel_flags_nowcs string
,icmodel_flags_nocalib string
,icmodel_flags_badcentroid string
,icmodel_dev_flux_flags_apcorr string
,icmodel_exp_flux_flags_apcorr string
,icmodel_flux_flags_apcorr string
,ideblend_psf_center_ra double
,ideblend_psf_center_dec double
,ideblend_psf_flux double
,ideblend_psf_mag float
,iblendedness_old float
,iblendedness_raw_flux float
,iblendedness_raw_flux_child double
,iblendedness_raw_mag_child float
,iblendedness_raw_flux_parent double
,iblendedness_raw_mag_parent float
,iblendedness_abs_flux float
,iblendedness_abs_flux_child double
,iblendedness_abs_mag_child float
,iblendedness_abs_flux_parent double
,iblendedness_abs_mag_parent float
,iblendedness_raw_shape_child_11 float
,iblendedness_raw_shape_child_22 float
,iblendedness_raw_shape_child_12 float
,iblendedness_raw_shape_parent_11 float
,iblendedness_raw_shape_parent_22 float
,iblendedness_raw_shape_parent_12 float
,iblendedness_abs_shape_child_11 float
,iblendedness_abs_shape_child_22 float
,iblendedness_abs_shape_child_12 float
,iblendedness_abs_shape_parent_11 float
,iblendedness_abs_shape_parent_22 float
,iblendedness_abs_shape_parent_12 float
,ideblend_deblended_as_psf string
,ideblend_too_many_peaks string
,ideblend_parent_too_big string
,ideblend_masked string
,ideblend_skipped string
,ideblend_ramped_template string
,ideblend_patched_template string
,ideblend_has_stray_flux string
,iblendedness_flags string
,iblendedness_flags_nocentroid string
,iblendedness_flags_noshape string
,icountinputs smallint
,iclassification_extendedness float
,iflags_negative string
,iflags_badcentroid string
,iflags_pixel_edge string
,iflags_pixel_interpolated_any string
,iflags_pixel_interpolated_center string
,iflags_pixel_saturated_any string
,iflags_pixel_saturated_center string
,iflags_pixel_cr_any string
,iflags_pixel_cr_center string
,iflags_pixel_bad string
,iflags_pixel_suspect_any string
,iflags_pixel_suspect_center string
,iflags_pixel_offimage string
,iflags_pixel_bright_object_center string
,iflags_pixel_clipped_any string
,iflags_pixel_bright_object_any string
,idetect_is_patch_inner string
,idetect_is_tract_inner string
,idetect_is_primary string
,icalib_psf_candidate string
,icalib_psf_used string
,zflux_naive double
,zmag_naive float
,zflux_naive_err double
,zmag_naive_err float
,zflux_naive_flags string
,zflux_sinc double
,zmag_sinc float
,zflux_sinc_err double
,zmag_sinc_err float
,zflux_sinc_flags string
,zflux_psf double
,zmag_psf float
,zflux_psf_err double
,zmag_psf_err float
,zflux_psf_apcorr float
,zflux_psf_apcorr_err float
,zflux_psf_flags string
,zflux_psf_flags_apcorr string
,zflux_kron double
,zmag_kron float
,zflux_kron_err double
,zmag_kron_err float
,zflux_kron_radius float
,zflux_kron_radiusforradius float
,zflux_kron_psfradius float
,zflux_kron_apcorr float
,zflux_kron_apcorr_err float
,zflux_kron_flags string
,zflux_kron_flags_edge string
,zflux_kron_flags_radius string
,zflux_kron_flags_smallradius string
,zflux_kron_flags_usedminimumradius string
,zflux_kron_flags_usedpsfradius string
,zflux_kron_flags_badshape string
,zflux_kron_flags_apcorr string
,zflux_gaussian double
,zmag_gaussian float
,zflux_gaussian_err double
,zmag_gaussian_err float
,zflux_gaussian_apcorr float
,zflux_gaussian_apcorr_err float
,zflux_gaussian_flags string
,zflux_gaussian_flags_apcorr string
,zcmodel_initial_flux double
,zcmodel_initial_mag float
,zcmodel_initial_flux_err double
,zcmodel_initial_mag_err float
,zcmodel_initial_flux_inner double
,zcmodel_initial_mag_inner float
,zcmodel_initial_ellipse_11 float
,zcmodel_initial_ellipse_22 float
,zcmodel_initial_ellipse_12 float
,zcmodel_initial_objective float
,zcmodel_initial_nonlinear0 float
,zcmodel_initial_nonlinear1 float
,zcmodel_initial_nonlinear2 float
,zcmodel_initial_fixed0 float
,zcmodel_initial_fixed1 float
,zcmodel_initial_niter int
,zcmodel_initial_time float
,zcmodel_exp_flux double
,zcmodel_exp_mag float
,zcmodel_exp_flux_err double
,zcmodel_exp_mag_err float
,zcmodel_exp_flux_inner double
,zcmodel_exp_mag_inner float
,zcmodel_exp_ellipse_11 float
,zcmodel_exp_ellipse_22 float
,zcmodel_exp_ellipse_12 float
,zcmodel_exp_objective float
,zcmodel_exp_nonlinear0 float
,zcmodel_exp_nonlinear1 float
,zcmodel_exp_nonlinear2 float
,zcmodel_exp_fixed0 float
,zcmodel_exp_fixed1 float
,zcmodel_exp_niter int
,zcmodel_exp_time float
,zcmodel_dev_flux double
,zcmodel_dev_mag float
,zcmodel_dev_flux_err double
,zcmodel_dev_mag_err float
,zcmodel_dev_flux_inner double
,zcmodel_dev_mag_inner float
,zcmodel_dev_ellipse_11 float
,zcmodel_dev_ellipse_22 float
,zcmodel_dev_ellipse_12 float
,zcmodel_dev_objective float
,zcmodel_dev_nonlinear0 float
,zcmodel_dev_nonlinear1 float
,zcmodel_dev_nonlinear2 float
,zcmodel_dev_fixed0 float
,zcmodel_dev_fixed1 float
,zcmodel_dev_niter int
,zcmodel_dev_time float
,zcmodel_center_ra double
,zcmodel_center_dec double
,zcmodel_flux double
,zcmodel_mag float
,zcmodel_flux_err double
,zcmodel_mag_err float
,zcmodel_flux_inner double
,zcmodel_mag_inner float
,zcmodel_fracdev float
,zcmodel_objective float
,zcmodel_ellipse_11 float
,zcmodel_ellipse_22 float
,zcmodel_ellipse_12 float
,zcmodel_region_initial_ellipse_11 float
,zcmodel_region_initial_ellipse_22 float
,zcmodel_region_initial_ellipse_12 float
,zcmodel_region_final_ellipse_11 float
,zcmodel_region_final_ellipse_22 float
,zcmodel_region_final_ellipse_12 float
,zcmodel_dev_flux_apcorr float
,zcmodel_dev_flux_apcorr_err float
,zcmodel_exp_flux_apcorr float
,zcmodel_exp_flux_apcorr_err float
,zcmodel_flux_apcorr float
,zcmodel_flux_apcorr_err float
,zcmodel_initial_flux_flags string
,zcmodel_initial_flags_trsmall string
,zcmodel_initial_flags_maxiter string
,zcmodel_initial_flags_numericerror string
,zcmodel_exp_flux_flags string
,zcmodel_exp_flags_trsmall string
,zcmodel_exp_flags_maxiter string
,zcmodel_exp_flags_numericerror string
,zcmodel_dev_flux_flags string
,zcmodel_dev_flags_trsmall string
,zcmodel_dev_flags_maxiter string
,zcmodel_dev_flags_numericerror string
,zcmodel_flux_flags string
,zcmodel_flags_region_maxarea string
,zcmodel_flags_region_maxbadpixelfraction string
,zcmodel_flags_region_usedfootprintarea string
,zcmodel_flags_region_usedpsfarea string
,zcmodel_flags_region_usedinitialellipsemin string
,zcmodel_flags_region_usedinitialellipsemax string
,zcmodel_flags_noshape string
,zcmodel_flags_smallshape string
,zcmodel_flags_nopsf string
,zcmodel_flags_nowcs string
,zcmodel_flags_nocalib string
,zcmodel_flags_badcentroid string
,zcmodel_dev_flux_flags_apcorr string
,zcmodel_exp_flux_flags_apcorr string
,zcmodel_flux_flags_apcorr string
,zdeblend_psf_center_ra double
,zdeblend_psf_center_dec double
,zdeblend_psf_flux double
,zdeblend_psf_mag float
,zblendedness_old float
,zblendedness_raw_flux float
,zblendedness_raw_flux_child double
,zblendedness_raw_mag_child float
,zblendedness_raw_flux_parent double
,zblendedness_raw_mag_parent float
,zblendedness_abs_flux float
,zblendedness_abs_flux_child double
,zblendedness_abs_mag_child float
,zblendedness_abs_flux_parent double
,zblendedness_abs_mag_parent float
,zblendedness_raw_shape_child_11 float
,zblendedness_raw_shape_child_22 float
,zblendedness_raw_shape_child_12 float
,zblendedness_raw_shape_parent_11 float
,zblendedness_raw_shape_parent_22 float
,zblendedness_raw_shape_parent_12 float
,zblendedness_abs_shape_child_11 float
,zblendedness_abs_shape_child_22 float
,zblendedness_abs_shape_child_12 float
,zblendedness_abs_shape_parent_11 float
,zblendedness_abs_shape_parent_22 float
,zblendedness_abs_shape_parent_12 float
,zdeblend_deblended_as_psf string
,zdeblend_too_many_peaks string
,zdeblend_parent_too_big string
,zdeblend_masked string
,zdeblend_skipped string
,zdeblend_ramped_template string
,zdeblend_patched_template string
,zdeblend_has_stray_flux string
,zblendedness_flags string
,zblendedness_flags_nocentroid string
,zblendedness_flags_noshape string
,zcountinputs smallint
,zclassification_extendedness float
,zflags_negative string
,zflags_badcentroid string
,zflags_pixel_edge string
,zflags_pixel_interpolated_any string
,zflags_pixel_interpolated_center string
,zflags_pixel_saturated_any string
,zflags_pixel_saturated_center string
,zflags_pixel_cr_any string
,zflags_pixel_cr_center string
,zflags_pixel_bad string
,zflags_pixel_suspect_any string
,zflags_pixel_suspect_center string
,zflags_pixel_offimage string
,zflags_pixel_bright_object_center string
,zflags_pixel_clipped_any string
,zflags_pixel_bright_object_any string
,zdetect_is_patch_inner string
,zdetect_is_tract_inner string
,zdetect_is_primary string
,zcalib_psf_candidate string
,zcalib_psf_used string
,yflux_naive double
,ymag_naive float
,yflux_naive_err double
,ymag_naive_err float
,yflux_naive_flags string
,yflux_sinc double
,ymag_sinc float
,yflux_sinc_err double
,ymag_sinc_err float
,yflux_sinc_flags string
,yflux_psf double
,ymag_psf float
,yflux_psf_err double
,ymag_psf_err float
,yflux_psf_apcorr float
,yflux_psf_apcorr_err float
,yflux_psf_flags string
,yflux_psf_flags_apcorr string
,yflux_kron double
,ymag_kron float
,yflux_kron_err double
,ymag_kron_err float
,yflux_kron_radius float
,yflux_kron_radiusforradius float
,yflux_kron_psfradius float
,yflux_kron_apcorr float
,yflux_kron_apcorr_err float
,yflux_kron_flags string
,yflux_kron_flags_edge string
,yflux_kron_flags_radius string
,yflux_kron_flags_smallradius string
,yflux_kron_flags_usedminimumradius string
,yflux_kron_flags_usedpsfradius string
,yflux_kron_flags_badshape string
,yflux_kron_flags_apcorr string
,yflux_gaussian double
,ymag_gaussian float
,yflux_gaussian_err double
,ymag_gaussian_err float
,yflux_gaussian_apcorr float
,yflux_gaussian_apcorr_err float
,yflux_gaussian_flags string
,yflux_gaussian_flags_apcorr string
,ycmodel_initial_flux double
,ycmodel_initial_mag float
,ycmodel_initial_flux_err double
,ycmodel_initial_mag_err float
,ycmodel_initial_flux_inner double
,ycmodel_initial_mag_inner float
,ycmodel_initial_ellipse_11 float
,ycmodel_initial_ellipse_22 float
,ycmodel_initial_ellipse_12 float
,ycmodel_initial_objective float
,ycmodel_initial_nonlinear0 float
,ycmodel_initial_nonlinear1 float
,ycmodel_initial_nonlinear2 float
,ycmodel_initial_fixed0 float
,ycmodel_initial_fixed1 float
,ycmodel_initial_niter int
,ycmodel_initial_time float
,ycmodel_exp_flux double
,ycmodel_exp_mag float
,ycmodel_exp_flux_err double
,ycmodel_exp_mag_err float
,ycmodel_exp_flux_inner double
,ycmodel_exp_mag_inner float
,ycmodel_exp_ellipse_11 float
,ycmodel_exp_ellipse_22 float
,ycmodel_exp_ellipse_12 float
,ycmodel_exp_objective float
,ycmodel_exp_nonlinear0 float
,ycmodel_exp_nonlinear1 float
,ycmodel_exp_nonlinear2 float
,ycmodel_exp_fixed0 float
,ycmodel_exp_fixed1 float
,ycmodel_exp_niter int
,ycmodel_exp_time float
,ycmodel_dev_flux double
,ycmodel_dev_mag float
,ycmodel_dev_flux_err double
,ycmodel_dev_mag_err float
,ycmodel_dev_flux_inner double
,ycmodel_dev_mag_inner float
,ycmodel_dev_ellipse_11 float
,ycmodel_dev_ellipse_22 float
,ycmodel_dev_ellipse_12 float
,ycmodel_dev_objective float
,ycmodel_dev_nonlinear0 float
,ycmodel_dev_nonlinear1 float
,ycmodel_dev_nonlinear2 float
,ycmodel_dev_fixed0 float
,ycmodel_dev_fixed1 float
,ycmodel_dev_niter int
,ycmodel_dev_time float
,ycmodel_center_ra double
,ycmodel_center_dec double
,ycmodel_flux double
,ycmodel_mag float
,ycmodel_flux_err double
,ycmodel_mag_err float
,ycmodel_flux_inner double
,ycmodel_mag_inner float
,ycmodel_fracdev float
,ycmodel_objective float
,ycmodel_ellipse_11 float
,ycmodel_ellipse_22 float
,ycmodel_ellipse_12 float
,ycmodel_region_initial_ellipse_11 float
,ycmodel_region_initial_ellipse_22 float
,ycmodel_region_initial_ellipse_12 float
,ycmodel_region_final_ellipse_11 float
,ycmodel_region_final_ellipse_22 float
,ycmodel_region_final_ellipse_12 float
,ycmodel_dev_flux_apcorr float
,ycmodel_dev_flux_apcorr_err float
,ycmodel_exp_flux_apcorr float
,ycmodel_exp_flux_apcorr_err float
,ycmodel_flux_apcorr float
,ycmodel_flux_apcorr_err float
,ycmodel_initial_flux_flags string
,ycmodel_initial_flags_trsmall string
,ycmodel_initial_flags_maxiter string
,ycmodel_initial_flags_numericerror string
,ycmodel_exp_flux_flags string
,ycmodel_exp_flags_trsmall string
,ycmodel_exp_flags_maxiter string
,ycmodel_exp_flags_numericerror string
,ycmodel_dev_flux_flags string
,ycmodel_dev_flags_trsmall string
,ycmodel_dev_flags_maxiter string
,ycmodel_dev_flags_numericerror string
,ycmodel_flux_flags string
,ycmodel_flags_region_maxarea string
,ycmodel_flags_region_maxbadpixelfraction string
,ycmodel_flags_region_usedfootprintarea string
,ycmodel_flags_region_usedpsfarea string
,ycmodel_flags_region_usedinitialellipsemin string
,ycmodel_flags_region_usedinitialellipsemax string
,ycmodel_flags_noshape string
,ycmodel_flags_smallshape string
,ycmodel_flags_nopsf string
,ycmodel_flags_nowcs string
,ycmodel_flags_nocalib string
,ycmodel_flags_badcentroid string
,ycmodel_dev_flux_flags_apcorr string
,ycmodel_exp_flux_flags_apcorr string
,ycmodel_flux_flags_apcorr string
,ydeblend_psf_center_ra double
,ydeblend_psf_center_dec double
,ydeblend_psf_flux double
,ydeblend_psf_mag float
,yblendedness_old float
,yblendedness_raw_flux float
,yblendedness_raw_flux_child double
,yblendedness_raw_mag_child float
,yblendedness_raw_flux_parent double
,yblendedness_raw_mag_parent float
,yblendedness_abs_flux float
,yblendedness_abs_flux_child double
,yblendedness_abs_mag_child float
,yblendedness_abs_flux_parent double
,yblendedness_abs_mag_parent float
,yblendedness_raw_shape_child_11 float
,yblendedness_raw_shape_child_22 float
,yblendedness_raw_shape_child_12 float
,yblendedness_raw_shape_parent_11 float
,yblendedness_raw_shape_parent_22 float
,yblendedness_raw_shape_parent_12 float
,yblendedness_abs_shape_child_11 float
,yblendedness_abs_shape_child_22 float
,yblendedness_abs_shape_child_12 float
,yblendedness_abs_shape_parent_11 float
,yblendedness_abs_shape_parent_22 float
,yblendedness_abs_shape_parent_12 float
,ydeblend_deblended_as_psf string
,ydeblend_too_many_peaks string
,ydeblend_parent_too_big string
,ydeblend_masked string
,ydeblend_skipped string
,ydeblend_ramped_template string
,ydeblend_patched_template string
,ydeblend_has_stray_flux string
,yblendedness_flags string
,yblendedness_flags_nocentroid string
,yblendedness_flags_noshape string
,ycountinputs smallint
,yclassification_extendedness float
,yflags_negative string
,yflags_badcentroid string
,yflags_pixel_edge string
,yflags_pixel_interpolated_any string
,yflags_pixel_interpolated_center string
,yflags_pixel_saturated_any string
,yflags_pixel_saturated_center string
,yflags_pixel_cr_any string
,yflags_pixel_cr_center string
,yflags_pixel_bad string
,yflags_pixel_suspect_any string
,yflags_pixel_suspect_center string
,yflags_pixel_offimage string
,yflags_pixel_bright_object_center string
,yflags_pixel_clipped_any string
,yflags_pixel_bright_object_any string
,ydetect_is_patch_inner string
,ydetect_is_tract_inner string
,ydetect_is_primary string
,ycalib_psf_candidate string
,ycalib_psf_used string
) ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
 WITH SERDEPROPERTIES (
 'separatorChar' = ',',
 'quoteChar' = '"',
 'escapeChar' = '\\')
 STORED AS TEXTFILE
 LOCATION '/user/suga/pdr1_hive/pdr1_wide_meas/';
